// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

// COMPONENT Slider3

lv_obj_t * ui_Slider3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Slider3;
    cui_Slider3 = lv_slider_create(comp_parent);
    lv_slider_set_value(cui_Slider3, 80, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_Slider3, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_Slider3, 65);
    lv_obj_set_height(cui_Slider3, 289);
    lv_obj_set_x(cui_Slider3, -7);
    lv_obj_set_y(cui_Slider3, 17);
    lv_obj_set_align(cui_Slider3, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(cui_Slider3, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_Slider3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(cui_Slider3, lv_color_hex(0x50FF7D), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(cui_Slider3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(cui_Slider3, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(cui_Slider3, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_Slider3, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_Slider3,
                                                                                               lv_obj_get_style_pad_right(cui_Slider3, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_SLIDER3_NUM);
    children[UI_COMP_SLIDER3_SLIDER3] = cui_Slider3;
    lv_obj_add_event_cb(cui_Slider3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Slider3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Slider3_create_hook(cui_Slider3);
    return cui_Slider3;
}

