// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _VOX_EFX_UI_COMP_HOOK_H
#define _VOX_EFX_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_IndicatorRight_create_hook(lv_obj_t * comp);
void ui_comp_Slider3_create_hook(lv_obj_t * comp);
void ui_comp_X32Meter_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
