// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

// COMPONENT X32Meter

lv_obj_t * ui_X32Meter_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_X32Meter;
    cui_X32Meter = lv_slider_create(comp_parent);
    lv_slider_set_range(cui_X32Meter, 0, 29);
    lv_slider_set_value(cui_X32Meter, 15, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_X32Meter) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_X32Meter, 0, LV_ANIM_OFF);
    lv_obj_set_width(cui_X32Meter, 33);
    lv_obj_set_height(cui_X32Meter, 289);
    lv_obj_set_x(cui_X32Meter, -143);
    lv_obj_set_y(cui_X32Meter, 5);
    lv_obj_set_align(cui_X32Meter, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(cui_X32Meter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_X32Meter, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_X32Meter, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_X32Meter, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_X32Meter,
                                                                                                lv_obj_get_style_pad_right(cui_X32Meter, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_X32METER_NUM);
    children[UI_COMP_X32METER_X32METER] = cui_X32Meter;
    lv_obj_add_event_cb(cui_X32Meter, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_X32Meter, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_X32Meter_create_hook(cui_X32Meter);
    return cui_X32Meter;
}

