// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

void ui_comp_IndicatorRight_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Slider3_create_hook(lv_obj_t * comp)
{
}

void ui_comp_X32Meter_create_hook(lv_obj_t * comp)
{
}
