// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _UI_COMP_INDICATORRIGHT_H
#define _UI_COMP_INDICATORRIGHT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT IndicatorRight
#define UI_COMP_INDICATORRIGHT_INDICATORRIGHT 0
#define _UI_COMP_INDICATORRIGHT_NUM 1
lv_obj_t * ui_IndicatorRight_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
