// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _UI_COMP_SLIDER3_H
#define _UI_COMP_SLIDER3_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Slider3
#define UI_COMP_SLIDER3_SLIDER3 0
#define _UI_COMP_SLIDER3_NUM 1
lv_obj_t * ui_Slider3_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
