// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

// COMPONENT IndicatorRight

lv_obj_t * ui_IndicatorRight_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_IndicatorRight;
    cui_IndicatorRight = lv_slider_create(comp_parent);
    lv_slider_set_range(cui_IndicatorRight, 0, 29);
    lv_slider_set_value(cui_IndicatorRight, 25, LV_ANIM_OFF);
    if(lv_slider_get_mode(cui_IndicatorRight) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(cui_IndicatorRight, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(cui_IndicatorRight, 33);
    lv_obj_set_height(cui_IndicatorRight, 289);
    lv_obj_set_align(cui_IndicatorRight, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(cui_IndicatorRight, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_IndicatorRight, lv_color_hex(0x272A33), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_IndicatorRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_IndicatorRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_IndicatorRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(cui_IndicatorRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_IndicatorRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_IndicatorRight, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_IndicatorRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_IndicatorRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_IndicatorRight, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_IndicatorRight, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_IndicatorRight, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_IndicatorRight,
                                                                                                      lv_obj_get_style_pad_right(cui_IndicatorRight, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_INDICATORRIGHT_NUM);
    children[UI_COMP_INDICATORRIGHT_INDICATORRIGHT] = cui_IndicatorRight;
    lv_obj_add_event_cb(cui_IndicatorRight, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_IndicatorRight, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_IndicatorRight_create_hook(cui_IndicatorRight);
    return cui_IndicatorRight;
}

