// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _UI_COMP_X32METER_H
#define _UI_COMP_X32METER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT X32Meter
#define UI_COMP_X32METER_X32METER 0
#define _UI_COMP_X32METER_NUM 1
lv_obj_t * ui_X32Meter_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
