// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_contStatus = NULL;
lv_obj_t * ui_contStatusLeft = NULL;
lv_obj_t * ui_uibtnBack = NULL;
lv_obj_t * ui_uiImagebtnBack = NULL;
lv_obj_t * ui_contStatusRight = NULL;
lv_obj_t * ui_uiimgWifi = NULL;
lv_obj_t * ui_contentArea = NULL;
lv_obj_t * ui_contHome = NULL;
lv_obj_t * ui_BGImageMain = NULL;
lv_obj_t * ui_contTileReverb = NULL;
lv_obj_t * ui_imgTileReverbBg = NULL;
lv_obj_t * ui_contTileDelay = NULL;
lv_obj_t * ui_imgTileDelayBg = NULL;
lv_obj_t * ui_contTileComp = NULL;
lv_obj_t * ui_imgTileCompBg = NULL;
lv_obj_t * ui_contTileEQ = NULL;
lv_obj_t * ui_imgTileEqBg = NULL;
lv_obj_t * ui_contTileSettings = NULL;
lv_obj_t * ui_imgTileSettingsBg = NULL;
lv_obj_t * ui_contDelay = NULL;
lv_obj_t * ui_contReverb = NULL;
lv_obj_t * ui_contComp = NULL;
lv_obj_t * ui_contEQ = NULL;
lv_obj_t * ui_contSettings = NULL;
lv_obj_t * ui_Image1 = NULL;
// event funtions

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Main, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatus = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_contStatus);
    lv_obj_set_width(ui_contStatus, 480);
    lv_obj_set_height(ui_contStatus, 32);
    lv_obj_set_align(ui_contStatus, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_contStatus, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatus, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_contStatus, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_contStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatus, lv_color_hex(0x121416), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatusLeft = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contStatusLeft);
    lv_obj_set_width(ui_contStatusLeft, 43);
    lv_obj_set_height(ui_contStatusLeft, 26);
    lv_obj_set_align(ui_contStatusLeft, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_contStatusLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatusLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contStatusLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatusLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatusLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uibtnBack = lv_button_create(ui_contStatusLeft);
    lv_obj_set_width(ui_uibtnBack, 44);
    lv_obj_set_height(ui_uibtnBack, 28);
    lv_obj_set_align(ui_uibtnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uibtnBack, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_uibtnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_uibtnBack, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uibtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_uibtnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_uibtnBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_uibtnBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_uibtnBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_uibtnBack, 40, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_uibtnBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_uibtnBack, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_uiImagebtnBack = lv_image_create(ui_uibtnBack);
    lv_image_set_src(ui_uiImagebtnBack, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_uiImagebtnBack, 24);
    lv_obj_set_height(ui_uiImagebtnBack, 24);
    lv_obj_set_align(ui_uiImagebtnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_uiImagebtnBack, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_uiImagebtnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contStatusRight = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contStatusRight);
    lv_obj_set_width(ui_contStatusRight, 24);
    lv_obj_set_height(ui_contStatusRight, 24);
    lv_obj_set_align(ui_contStatusRight, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_contStatusRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatusRight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_contStatusRight, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_contStatusRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatusRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatusRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_uiimgWifi = lv_image_create(ui_contStatusRight);
    lv_image_set_src(ui_uiimgWifi, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_uiimgWifi, 24);
    lv_obj_set_height(ui_uiimgWifi, 24);
    lv_obj_set_align(ui_uiimgWifi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_uiimgWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_uiimgWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_uiimgWifi, LV_IMAGE_ALIGN_RIGHT_MID);

    ui_contentArea = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_contentArea);
    lv_obj_set_width(ui_contentArea, 480);
    lv_obj_set_height(ui_contentArea, 288);
    lv_obj_set_x(ui_contentArea, 0);
    lv_obj_set_y(ui_contentArea, 32);
    lv_obj_set_align(ui_contentArea, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_contentArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contentArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHome = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contHome);
    lv_obj_set_width(ui_contHome, 480);
    lv_obj_set_height(ui_contHome, 288);
    lv_obj_set_align(ui_contHome, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHome, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contHome, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contHome, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BGImageMain = lv_image_create(ui_contHome);
    lv_image_set_src(ui_BGImageMain, &ui_img_bgpanel_home_png);
    lv_obj_set_width(ui_BGImageMain, 480);
    lv_obj_set_height(ui_BGImageMain, 288);
    lv_obj_add_flag(ui_BGImageMain, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BGImageMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTileReverb = lv_obj_create(ui_contHome);
    lv_obj_remove_style_all(ui_contTileReverb);
    lv_obj_set_width(ui_contTileReverb, 190);
    lv_obj_set_height(ui_contTileReverb, 107);
    lv_obj_set_x(ui_contTileReverb, -120);
    lv_obj_set_y(ui_contTileReverb, -67);
    lv_obj_set_align(ui_contTileReverb, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTileReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTileReverbBg = lv_image_create(ui_contTileReverb);
    lv_image_set_src(ui_imgTileReverbBg, &ui_img_reverbpedal_png);
    lv_obj_set_width(ui_imgTileReverbBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTileReverbBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTileReverbBg, -47);
    lv_obj_set_y(ui_imgTileReverbBg, 0);
    lv_obj_set_align(ui_imgTileReverbBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTileReverbBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTileReverbBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTileDelay = lv_obj_create(ui_contHome);
    lv_obj_remove_style_all(ui_contTileDelay);
    lv_obj_set_width(ui_contTileDelay, 163);
    lv_obj_set_height(ui_contTileDelay, 107);
    lv_obj_set_x(ui_contTileDelay, 67);
    lv_obj_set_y(ui_contTileDelay, -67);
    lv_obj_set_align(ui_contTileDelay, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTileDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTileDelayBg = lv_image_create(ui_contTileDelay);
    lv_image_set_src(ui_imgTileDelayBg, &ui_img_delaypedal_png);
    lv_obj_set_width(ui_imgTileDelayBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTileDelayBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTileDelayBg, -47);
    lv_obj_set_y(ui_imgTileDelayBg, 0);
    lv_obj_set_align(ui_imgTileDelayBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTileDelayBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTileDelayBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTileComp = lv_obj_create(ui_contHome);
    lv_obj_remove_style_all(ui_contTileComp);
    lv_obj_set_width(ui_contTileComp, 190);
    lv_obj_set_height(ui_contTileComp, 107);
    lv_obj_set_x(ui_contTileComp, -120);
    lv_obj_set_y(ui_contTileComp, 46);
    lv_obj_set_align(ui_contTileComp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTileComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTileCompBg = lv_image_create(ui_contTileComp);
    lv_image_set_src(ui_imgTileCompBg, &ui_img_comppedal_png);
    lv_obj_set_width(ui_imgTileCompBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTileCompBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTileCompBg, -47);
    lv_obj_set_y(ui_imgTileCompBg, 0);
    lv_obj_set_align(ui_imgTileCompBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTileCompBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTileCompBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTileEQ = lv_obj_create(ui_contHome);
    lv_obj_remove_style_all(ui_contTileEQ);
    lv_obj_set_width(ui_contTileEQ, 163);
    lv_obj_set_height(ui_contTileEQ, 107);
    lv_obj_set_x(ui_contTileEQ, 67);
    lv_obj_set_y(ui_contTileEQ, 54);
    lv_obj_set_align(ui_contTileEQ, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTileEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTileEqBg = lv_image_create(ui_contTileEQ);
    lv_image_set_src(ui_imgTileEqBg, &ui_img_eqpedal_png);
    lv_obj_set_width(ui_imgTileEqBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTileEqBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTileEqBg, -47);
    lv_obj_set_y(ui_imgTileEqBg, 0);
    lv_obj_set_align(ui_imgTileEqBg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgTileEqBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTileEqBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contTileSettings = lv_obj_create(ui_contHome);
    lv_obj_remove_style_all(ui_contTileSettings);
    lv_obj_set_width(ui_contTileSettings, 285);
    lv_obj_set_height(ui_contTileSettings, 27);
    lv_obj_set_x(ui_contTileSettings, 0);
    lv_obj_set_y(ui_contTileSettings, 126);
    lv_obj_set_align(ui_contTileSettings, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contTileSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgTileSettingsBg = lv_image_create(ui_contTileSettings);
    lv_image_set_src(ui_imgTileSettingsBg, &ui_img_icn_settings_png);
    lv_obj_set_width(ui_imgTileSettingsBg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgTileSettingsBg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgTileSettingsBg, 9);
    lv_obj_set_y(ui_imgTileSettingsBg, 3);
    lv_obj_set_align(ui_imgTileSettingsBg, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_imgTileSettingsBg, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgTileSettingsBg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contDelay = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contDelay);
    lv_obj_set_width(ui_contDelay, 480);
    lv_obj_set_height(ui_contDelay, 288);
    lv_obj_set_align(ui_contDelay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contDelay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contDelay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contDelay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contReverb = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contReverb);
    lv_obj_set_width(ui_contReverb, 480);
    lv_obj_set_height(ui_contReverb, 288);
    lv_obj_set_align(ui_contReverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contReverb, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contReverb, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contReverb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contComp = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contComp);
    lv_obj_set_width(ui_contComp, 480);
    lv_obj_set_height(ui_contComp, 288);
    lv_obj_set_align(ui_contComp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contComp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contComp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contEQ = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contEQ);
    lv_obj_set_width(ui_contEQ, 480);
    lv_obj_set_height(ui_contEQ, 288);
    lv_obj_set_align(ui_contEQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contEQ, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contEQ, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contSettings = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contSettings);
    lv_obj_set_width(ui_contSettings, 480);
    lv_obj_set_height(ui_contSettings, 288);
    lv_obj_set_align(ui_contSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_contSettings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_contSettings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_contSettings);
    lv_image_set_src(ui_Image1, &ui_img_delaypedal_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_contStatus = NULL;
    ui_contStatusLeft = NULL;
    ui_uibtnBack = NULL;
    ui_uiImagebtnBack = NULL;
    ui_contStatusRight = NULL;
    ui_uiimgWifi = NULL;
    ui_contentArea = NULL;
    ui_contHome = NULL;
    ui_BGImageMain = NULL;
    ui_contTileReverb = NULL;
    ui_imgTileReverbBg = NULL;
    ui_contTileDelay = NULL;
    ui_imgTileDelayBg = NULL;
    ui_contTileComp = NULL;
    ui_imgTileCompBg = NULL;
    ui_contTileEQ = NULL;
    ui_imgTileEqBg = NULL;
    ui_contTileSettings = NULL;
    ui_imgTileSettingsBg = NULL;
    ui_contDelay = NULL;
    ui_contReverb = NULL;
    ui_contComp = NULL;
    ui_contEQ = NULL;
    ui_contSettings = NULL;
    ui_Image1 = NULL;

}
