// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_NavBar;
extern lv_obj_t * ui_NavContainer;
extern void ui_event_btnReverbPage(lv_event_t * e);
extern lv_obj_t * ui_btnReverbPage;
extern lv_obj_t * ui_Label2;
extern void ui_event_btnDelayPage(lv_event_t * e);
extern lv_obj_t * ui_btnDelayPage;
extern lv_obj_t * ui_Label1;
extern void ui_event_btnDynamicsPage(lv_event_t * e);
extern lv_obj_t * ui_btnDynamicsPage;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnEQPage(lv_event_t * e);
extern lv_obj_t * ui_btnEQPage;
extern lv_obj_t * ui_Label4;
extern void ui_event_btnSetupPage(lv_event_t * e);
extern lv_obj_t * ui_btnSetupPage;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_ContentContainer;
extern lv_obj_t * ui_pnlReverb;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_pnlDelay;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_pnlDynamics;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_pnlEQ;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_pnlSetup;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NavContainer;
extern lv_obj_t * uic_btnReverbPage;
extern lv_obj_t * uic_Label2;
extern lv_obj_t * uic_btnDelayPage;
extern lv_obj_t * uic_btnEQPage;
extern lv_obj_t * uic_btnSetupPage;
extern lv_obj_t * uic_ContentContainer;
extern lv_obj_t * uic_pnlReverb;
extern lv_obj_t * uic_pnlDelay;
extern lv_obj_t * uic_pnlDynamics;
extern lv_obj_t * uic_pnlEQ;
extern lv_obj_t * uic_pnlSetup;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

