// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_contStatus = NULL;
lv_obj_t * ui_contStatusLeft = NULL;
lv_obj_t * ui_contStatusMid = NULL;
lv_obj_t * ui_contStatusRight = NULL;
lv_obj_t * ui_imgWifiDisconnected = NULL;
lv_obj_t * ui_imgWifiConnecting = NULL;
lv_obj_t * ui_imgWifiConnected = NULL;
lv_obj_t * ui_contentArea = NULL;
lv_obj_t * ui_contNavigation = NULL;
lv_obj_t * ui_btnCompressor = NULL;
lv_obj_t * ui_ImageComp = NULL;
lv_obj_t * ui_btnDelay = NULL;
lv_obj_t * ui_ImageDelay = NULL;
lv_obj_t * ui_btnReverb = NULL;
lv_obj_t * ui_ImageReverb = NULL;
lv_obj_t * ui_btnEQ = NULL;
lv_obj_t * ui_ImageEQ = NULL;
lv_obj_t * ui_btnSetup = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_LabelSetup = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_pnlComp = NULL;
lv_obj_t * ui_btnBackComp = NULL;
lv_obj_t * ui_ImageBtnBackComp = NULL;
lv_obj_t * ui_pnlDelay = NULL;
lv_obj_t * ui_btnBackDelay = NULL;
lv_obj_t * ui_ImageBtnBackDelay = NULL;
lv_obj_t * ui_pnlReverb = NULL;
lv_obj_t * ui_btnBackReverb = NULL;
lv_obj_t * ui_ImageBtnBackReverb = NULL;
lv_obj_t * ui_pnlEQ = NULL;
lv_obj_t * ui_btnBackEQ = NULL;
lv_obj_t * ui_ImageBtnBackEQ = NULL;
lv_obj_t * ui_pnlSettings = NULL;
lv_obj_t * ui_btnBackSettings = NULL;
lv_obj_t * ui_ImageBtnBackSettings = NULL;
// event funtions

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Main, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_Main, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatus = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_contStatus);
    lv_obj_set_width(ui_contStatus, 480);
    lv_obj_set_height(ui_contStatus, 32);
    lv_obj_set_align(ui_contStatus, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_contStatus, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatus, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_contStatus, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_contStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatus, lv_color_hex(0x0D0D0D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contStatus, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contStatus, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contStatus, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatusLeft = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contStatusLeft);
    lv_obj_set_width(ui_contStatusLeft, 43);
    lv_obj_set_height(ui_contStatusLeft, 26);
    lv_obj_set_align(ui_contStatusLeft, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_contStatusLeft, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatusLeft, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contStatusLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatusLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatusLeft, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatusMid = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contStatusMid);
    lv_obj_set_width(ui_contStatusMid, lv_pct(50));
    lv_obj_set_height(ui_contStatusMid, lv_pct(100));
    lv_obj_set_align(ui_contStatusMid, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contStatusMid, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatusMid, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contStatusMid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatusMid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatusMid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contStatusRight = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contStatusRight);
    lv_obj_set_width(ui_contStatusRight, 42);
    lv_obj_set_height(ui_contStatusRight, 24);
    lv_obj_set_align(ui_contStatusRight, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_contStatusRight, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_contStatusRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contStatusRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatusRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifiDisconnected = lv_image_create(ui_contStatusRight);
    lv_image_set_src(ui_imgWifiDisconnected, &ui_img_wifi_disconnected_png);
    lv_obj_set_width(ui_imgWifiDisconnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifiDisconnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWifiDisconnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifiDisconnected, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWifiDisconnected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_imgWifiDisconnected, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgWifiDisconnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgWifiDisconnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_imgWifiDisconnected, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_imgWifiDisconnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifiConnecting = lv_image_create(ui_contStatusRight);
    lv_image_set_src(ui_imgWifiConnecting, &ui_img_wifi_connecting_png);
    lv_obj_set_width(ui_imgWifiConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifiConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWifiConnecting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifiConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_imgWifiConnecting,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_image_set_inner_align(ui_imgWifiConnecting, LV_IMAGE_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_imgWifiConnecting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgWifiConnecting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgWifiConnecting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgWifiConnecting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgWifiConnecting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWifiConnected = lv_image_create(ui_contStatusRight);
    lv_image_set_src(ui_imgWifiConnected, &ui_img_wifi_connected_png);
    lv_obj_set_width(ui_imgWifiConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWifiConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWifiConnected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWifiConnected, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_imgWifiConnected,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_image_set_inner_align(ui_imgWifiConnected, LV_IMAGE_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_imgWifiConnected, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_imgWifiConnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgWifiConnected, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgWifiConnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgWifiConnected, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contentArea = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_contentArea);
    lv_obj_set_width(ui_contentArea, 480);
    lv_obj_set_height(ui_contentArea, 288);
    lv_obj_set_x(ui_contentArea, 0);
    lv_obj_set_y(ui_contentArea, 32);
    lv_obj_set_align(ui_contentArea, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_contentArea, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contentArea, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contentArea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contNavigation = lv_obj_create(ui_contentArea);
    lv_obj_remove_style_all(ui_contNavigation);
    lv_obj_set_width(ui_contNavigation, lv_pct(100));
    lv_obj_set_height(ui_contNavigation, lv_pct(100));
    lv_obj_set_x(ui_contNavigation, -2);
    lv_obj_set_y(ui_contNavigation, 1);
    lv_obj_set_align(ui_contNavigation, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contNavigation, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_contNavigation, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contNavigation, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contNavigation, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contNavigation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contNavigation, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contNavigation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contNavigation, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCompressor = lv_button_create(ui_contNavigation);
    lv_obj_set_width(ui_btnCompressor, 110);
    lv_obj_set_height(ui_btnCompressor, 181);
    lv_obj_set_x(ui_btnCompressor, -152);
    lv_obj_set_y(ui_btnCompressor, -3);
    lv_obj_set_align(ui_btnCompressor, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnCompressor, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnCompressor, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_btnCompressor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnCompressor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnCompressor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnCompressor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnCompressor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageComp = lv_image_create(ui_btnCompressor);
    lv_image_set_src(ui_ImageComp, &ui_img_comppedal_png);
    lv_obj_set_width(ui_ImageComp, lv_pct(100));
    lv_obj_set_height(ui_ImageComp, lv_pct(100));
    lv_obj_set_x(ui_ImageComp, -13);
    lv_obj_set_y(ui_ImageComp, -6);
    lv_obj_set_align(ui_ImageComp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageComp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnDelay = lv_button_create(ui_contNavigation);
    lv_obj_set_width(ui_btnDelay, 110);
    lv_obj_set_height(ui_btnDelay, 181);
    lv_obj_set_x(ui_btnDelay, -31);
    lv_obj_set_y(ui_btnDelay, -3);
    lv_obj_set_align(ui_btnDelay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnDelay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnDelay, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_btnDelay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnDelay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnDelay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDelay = lv_image_create(ui_btnDelay);
    lv_image_set_src(ui_ImageDelay, &ui_img_delaypedal_png);
    lv_obj_set_width(ui_ImageDelay, lv_pct(100));
    lv_obj_set_height(ui_ImageDelay, lv_pct(100));
    lv_obj_set_x(ui_ImageDelay, -16);
    lv_obj_set_y(ui_ImageDelay, 1);
    lv_obj_set_align(ui_ImageDelay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDelay, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnReverb = lv_button_create(ui_contNavigation);
    lv_obj_set_width(ui_btnReverb, 110);
    lv_obj_set_height(ui_btnReverb, 181);
    lv_obj_set_x(ui_btnReverb, 91);
    lv_obj_set_y(ui_btnReverb, -6);
    lv_obj_set_align(ui_btnReverb, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnReverb, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnReverb, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_btnReverb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnReverb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnReverb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageReverb = lv_image_create(ui_btnReverb);
    lv_image_set_src(ui_ImageReverb, &ui_img_reverbpedal_png);
    lv_obj_set_width(ui_ImageReverb, lv_pct(100));
    lv_obj_set_height(ui_ImageReverb, lv_pct(100));
    lv_obj_set_x(ui_ImageReverb, -11);
    lv_obj_set_y(ui_ImageReverb, 0);
    lv_obj_set_align(ui_ImageReverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageReverb, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnEQ = lv_button_create(ui_contNavigation);
    lv_obj_set_width(ui_btnEQ, 110);
    lv_obj_set_height(ui_btnEQ, 181);
    lv_obj_set_x(ui_btnEQ, 189);
    lv_obj_set_y(ui_btnEQ, -6);
    lv_obj_set_align(ui_btnEQ, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnEQ, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnEQ, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_btnEQ, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnEQ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageEQ = lv_image_create(ui_btnEQ);
    lv_image_set_src(ui_ImageEQ, &ui_img_eqpedal_png);
    lv_obj_set_width(ui_ImageEQ, lv_pct(100));
    lv_obj_set_height(ui_ImageEQ, lv_pct(100));
    lv_obj_set_x(ui_ImageEQ, -13);
    lv_obj_set_y(ui_ImageEQ, -3);
    lv_obj_set_align(ui_ImageEQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageEQ, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnSetup = lv_button_create(ui_contNavigation);
    lv_obj_set_width(ui_btnSetup, 285);
    lv_obj_set_height(ui_btnSetup, 83);
    lv_obj_set_x(ui_btnSetup, 203);
    lv_obj_set_y(ui_btnSetup, -119);
    lv_obj_set_align(ui_btnSetup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSetup, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnSetup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnSetup, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnSetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnSetup, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_btnSetup);
    lv_image_set_src(ui_Image4, &ui_img_button_250_50_png);
    lv_obj_set_width(ui_Image4, lv_pct(100));
    lv_obj_set_height(ui_Image4, lv_pct(100));
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSetup = lv_label_create(ui_Image4);
    lv_obj_set_width(ui_LabelSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSetup, "GLOBAL SETTINGS");

    ui_Image5 = lv_image_create(ui_Image4);
    lv_image_set_src(ui_Image5, &ui_img_icn_settings_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, 25);
    lv_obj_set_y(ui_Image5, -1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pnlComp = lv_obj_create(ui_contentArea);
    lv_obj_set_width(ui_pnlComp, 480);
    lv_obj_set_height(ui_pnlComp, 288);
    lv_obj_set_x(ui_pnlComp, 0);
    lv_obj_set_y(ui_pnlComp, -1);
    lv_obj_set_align(ui_pnlComp, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_pnlComp, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_pnlComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlComp, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlComp, lv_color_hex(0xF51C10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlComp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackComp = lv_button_create(ui_pnlComp);
    lv_obj_set_width(ui_btnBackComp, 67);
    lv_obj_set_height(ui_btnBackComp, 82);
    lv_obj_set_x(ui_btnBackComp, -10);
    lv_obj_set_y(ui_btnBackComp, -3);
    lv_obj_set_align(ui_btnBackComp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnBackComp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackComp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnBackComp = lv_image_create(ui_btnBackComp);
    lv_image_set_src(ui_ImageBtnBackComp, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_ImageBtnBackComp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBtnBackComp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBtnBackComp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnBackComp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnBackComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImageBtnBackComp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageBtnBackComp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlDelay = lv_obj_create(ui_contentArea);
    lv_obj_set_width(ui_pnlDelay, 480);
    lv_obj_set_height(ui_pnlDelay, 288);
    lv_obj_set_x(ui_pnlDelay, 0);
    lv_obj_set_y(ui_pnlDelay, -1);
    lv_obj_set_align(ui_pnlDelay, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_pnlDelay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_pnlDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlDelay, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlDelay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlDelay, lv_color_hex(0x8DE64C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlDelay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackDelay = lv_button_create(ui_pnlDelay);
    lv_obj_set_width(ui_btnBackDelay, 67);
    lv_obj_set_height(ui_btnBackDelay, 82);
    lv_obj_set_x(ui_btnBackDelay, -10);
    lv_obj_set_y(ui_btnBackDelay, -3);
    lv_obj_set_align(ui_btnBackDelay, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnBackDelay, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackDelay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackDelay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnBackDelay = lv_image_create(ui_btnBackDelay);
    lv_image_set_src(ui_ImageBtnBackDelay, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_ImageBtnBackDelay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBtnBackDelay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBtnBackDelay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnBackDelay, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnBackDelay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImageBtnBackDelay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageBtnBackDelay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlReverb = lv_obj_create(ui_contentArea);
    lv_obj_set_width(ui_pnlReverb, 480);
    lv_obj_set_height(ui_pnlReverb, 288);
    lv_obj_set_x(ui_pnlReverb, 0);
    lv_obj_set_y(ui_pnlReverb, -1);
    lv_obj_set_align(ui_pnlReverb, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_pnlReverb, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_pnlReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlReverb, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlReverb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlReverb, lv_color_hex(0x31D2D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlReverb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackReverb = lv_button_create(ui_pnlReverb);
    lv_obj_set_width(ui_btnBackReverb, 67);
    lv_obj_set_height(ui_btnBackReverb, 82);
    lv_obj_set_x(ui_btnBackReverb, -10);
    lv_obj_set_y(ui_btnBackReverb, -3);
    lv_obj_set_align(ui_btnBackReverb, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnBackReverb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackReverb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackReverb, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnBackReverb = lv_image_create(ui_btnBackReverb);
    lv_image_set_src(ui_ImageBtnBackReverb, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_ImageBtnBackReverb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBtnBackReverb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBtnBackReverb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnBackReverb, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnBackReverb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImageBtnBackReverb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageBtnBackReverb, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlEQ = lv_obj_create(ui_contentArea);
    lv_obj_set_width(ui_pnlEQ, 480);
    lv_obj_set_height(ui_pnlEQ, 288);
    lv_obj_set_x(ui_pnlEQ, 0);
    lv_obj_set_y(ui_pnlEQ, -1);
    lv_obj_set_align(ui_pnlEQ, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_pnlEQ, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_pnlEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlEQ, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlEQ, lv_color_hex(0x8606C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackEQ = lv_button_create(ui_pnlEQ);
    lv_obj_set_width(ui_btnBackEQ, 67);
    lv_obj_set_height(ui_btnBackEQ, 82);
    lv_obj_set_x(ui_btnBackEQ, -10);
    lv_obj_set_y(ui_btnBackEQ, -3);
    lv_obj_set_align(ui_btnBackEQ, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnBackEQ, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackEQ, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnBackEQ = lv_image_create(ui_btnBackEQ);
    lv_image_set_src(ui_ImageBtnBackEQ, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_ImageBtnBackEQ, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBtnBackEQ, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBtnBackEQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnBackEQ, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnBackEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImageBtnBackEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageBtnBackEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSettings = lv_obj_create(ui_contentArea);
    lv_obj_set_width(ui_pnlSettings, 480);
    lv_obj_set_height(ui_pnlSettings, 288);
    lv_obj_set_x(ui_pnlSettings, 0);
    lv_obj_set_y(ui_pnlSettings, -1);
    lv_obj_set_align(ui_pnlSettings, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_pnlSettings, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_pnlSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlSettings, lv_color_hex(0x2C2C2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSettings, lv_color_hex(0xDA8007), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackSettings = lv_button_create(ui_pnlSettings);
    lv_obj_set_width(ui_btnBackSettings, 67);
    lv_obj_set_height(ui_btnBackSettings, 82);
    lv_obj_set_x(ui_btnBackSettings, -10);
    lv_obj_set_y(ui_btnBackSettings, -3);
    lv_obj_set_align(ui_btnBackSettings, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnBackSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBtnBackSettings = lv_image_create(ui_btnBackSettings);
    lv_image_set_src(ui_ImageBtnBackSettings, &ui_img_arrow_left_24_png);
    lv_obj_set_width(ui_ImageBtnBackSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBtnBackSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBtnBackSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBtnBackSettings, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBtnBackSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImageBtnBackSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageBtnBackSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_contStatus = NULL;
    ui_contStatusLeft = NULL;
    ui_contStatusMid = NULL;
    ui_contStatusRight = NULL;
    ui_imgWifiDisconnected = NULL;
    ui_imgWifiConnecting = NULL;
    ui_imgWifiConnected = NULL;
    ui_contentArea = NULL;
    ui_contNavigation = NULL;
    ui_btnCompressor = NULL;
    ui_ImageComp = NULL;
    ui_btnDelay = NULL;
    ui_ImageDelay = NULL;
    ui_btnReverb = NULL;
    ui_ImageReverb = NULL;
    ui_btnEQ = NULL;
    ui_ImageEQ = NULL;
    ui_btnSetup = NULL;
    ui_Image4 = NULL;
    ui_LabelSetup = NULL;
    ui_Image5 = NULL;
    ui_pnlComp = NULL;
    ui_btnBackComp = NULL;
    ui_ImageBtnBackComp = NULL;
    ui_pnlDelay = NULL;
    ui_btnBackDelay = NULL;
    ui_ImageBtnBackDelay = NULL;
    ui_pnlReverb = NULL;
    ui_btnBackReverb = NULL;
    ui_ImageBtnBackReverb = NULL;
    ui_pnlEQ = NULL;
    ui_btnBackEQ = NULL;
    ui_ImageBtnBackEQ = NULL;
    ui_pnlSettings = NULL;
    ui_btnBackSettings = NULL;
    ui_ImageBtnBackSettings = NULL;

}
