// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_contStatus;
extern lv_obj_t * ui_contStatusLeft;
extern lv_obj_t * ui_contStatusMid;
extern lv_obj_t * ui_contStatusRight;
extern lv_obj_t * ui_imgWifiDisconnected;
extern lv_obj_t * ui_imgWifiConnecting;
extern lv_obj_t * ui_imgWifiConnected;
extern lv_obj_t * ui_contentArea;
extern lv_obj_t * ui_contNavigation;
extern lv_obj_t * ui_btnCompressor;
extern lv_obj_t * ui_ImageComp;
extern lv_obj_t * ui_btnDelay;
extern lv_obj_t * ui_ImageDelay;
extern lv_obj_t * ui_btnReverb;
extern lv_obj_t * ui_ImageReverb;
extern lv_obj_t * ui_btnEQ;
extern lv_obj_t * ui_ImageEQ;
extern lv_obj_t * ui_btnSetup;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_LabelSetup;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_pnlComp;
extern lv_obj_t * ui_btnBackComp;
extern lv_obj_t * ui_ImageBtnBackComp;
extern lv_obj_t * ui_pnlDelay;
extern lv_obj_t * ui_btnBackDelay;
extern lv_obj_t * ui_ImageBtnBackDelay;
extern lv_obj_t * ui_pnlReverb;
extern lv_obj_t * ui_btnBackReverb;
extern lv_obj_t * ui_ImageBtnBackReverb;
extern lv_obj_t * ui_pnlEQ;
extern lv_obj_t * ui_btnBackEQ;
extern lv_obj_t * ui_ImageBtnBackEQ;
extern lv_obj_t * ui_pnlSettings;
extern lv_obj_t * ui_btnBackSettings;
extern lv_obj_t * ui_ImageBtnBackSettings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

