// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_contStatus;
extern lv_obj_t * ui_contStatusLeft;
extern lv_obj_t * ui_contStatusMid;
extern lv_obj_t * ui_contStatusRight;
extern lv_obj_t * ui_imgWifiDisconnected;
extern lv_obj_t * ui_imgWifiConnecting;
extern lv_obj_t * ui_imgWifiConnected;
extern lv_obj_t * ui_contentArea;
extern lv_obj_t * ui_contNavigation;
extern lv_obj_t * ui_btnCompressor;
extern lv_obj_t * ui_ImageComp;
extern lv_obj_t * ui_btnDelay;
extern lv_obj_t * ui_ImageDelay;
extern lv_obj_t * ui_btnReverb;
extern lv_obj_t * ui_ImageReverb;
extern lv_obj_t * ui_btnEQ;
extern lv_obj_t * ui_ImageEQ;
extern lv_obj_t * ui_btnSetup;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_LabelSetup;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_pnlComp;
extern lv_obj_t * ui_CompHeaderBar;
extern lv_obj_t * ui_btnBackComp;
extern lv_obj_t * ui_ImageBtnBackComp;
extern lv_obj_t * ui_lblComp;
extern lv_obj_t * ui_CompOnBypass;
extern lv_obj_t * ui_contCompSettings;
extern lv_obj_t * ui_contSliderCompThreshold;
extern lv_obj_t * ui_lblCompThresholdName;
extern lv_obj_t * ui_sliderCompThreshold;
extern lv_obj_t * ui_lblCompThresholdValue;
extern lv_obj_t * ui_contSliderCompRatio;
extern lv_obj_t * ui_lblCompRatioName;
extern lv_obj_t * ui_sliderCompRatio;
extern lv_obj_t * ui_lblCompSlider2Value;
extern lv_obj_t * ui_contSliderCompAttack;
extern lv_obj_t * ui_lblCompAttackName;
extern lv_obj_t * ui_sliderCompAttack;
extern lv_obj_t * ui_lblCompAttackValue;
extern lv_obj_t * ui_contSliderCompRelease;
extern lv_obj_t * ui_lblCompReleaseName;
extern lv_obj_t * ui_sliderCompRelease;
extern lv_obj_t * ui_lblCompReleaseValue;
extern lv_obj_t * ui_contSliderCompGain;
extern lv_obj_t * ui_lblCompGainName;
extern lv_obj_t * ui_sliderCompGain;
extern lv_obj_t * ui_lblCompGainValue;
extern lv_obj_t * ui_pnlDelay;
extern lv_obj_t * ui_DelayHeaderBar;
extern lv_obj_t * ui_btnBackDelay;
extern lv_obj_t * ui_ImageBtnBackDelay;
extern lv_obj_t * ui_lblDelay;
extern lv_obj_t * ui_DelayOnBypass;
extern lv_obj_t * ui_contDelaySettings;
extern lv_obj_t * ui_contSliderDelayTime;
extern lv_obj_t * ui_lblDelayTimeName;
extern lv_obj_t * ui_sliderDelayTime;
extern lv_obj_t * ui_lblDelayTimeValue;
extern lv_obj_t * ui_contSliderDelayFeedback;
extern lv_obj_t * ui_lblDelayFeedbackName;
extern lv_obj_t * ui_sliderDelayFeedback;
extern lv_obj_t * ui_lblDelayFeedbackValue;
extern lv_obj_t * ui_pnlReverb;
extern lv_obj_t * ui_ReverbHeaderBar;
extern lv_obj_t * ui_btnBackReverb;
extern lv_obj_t * ui_ImageBtnBackReverb;
extern lv_obj_t * ui_lblReverb;
extern lv_obj_t * ui_ReverbOnBypass;
extern lv_obj_t * ui_contReverbSettings;
extern lv_obj_t * ui_contSliderReverbPreDelay;
extern lv_obj_t * ui_lblReverbPDelayName;
extern lv_obj_t * ui_sliderReverbPDelay;
extern lv_obj_t * ui_lblReverbPDelayValue;
extern lv_obj_t * ui_contSliderReverbMix;
extern lv_obj_t * ui_lblReverbMixName;
extern lv_obj_t * ui_sliderReverbMix;
extern lv_obj_t * ui_lblReverbMixValue;
extern lv_obj_t * ui_contSliderReverbSize;
extern lv_obj_t * ui_lblReverbSizeName;
extern lv_obj_t * ui_sliderReverbSize;
extern lv_obj_t * ui_lblReverbSizeValue;
extern lv_obj_t * ui_contSliderReverbDamp;
extern lv_obj_t * ui_lblReverbDampName;
extern lv_obj_t * ui_sliderReverbDamp;
extern lv_obj_t * ui_lblReverbDampValue;
extern lv_obj_t * ui_pnlEQ;
extern lv_obj_t * ui_EqHeaderBar;
extern lv_obj_t * ui_btnBackEq;
extern lv_obj_t * ui_ImageBtnBackEq;
extern lv_obj_t * ui_EqLabel;
extern lv_obj_t * ui_EqOnBypass;
extern lv_obj_t * ui_contEQSettings;
extern lv_obj_t * ui_contSliderEqHPF;
extern lv_obj_t * ui_lblEqHPFName;
extern lv_obj_t * ui_sliderEqHPF;
extern lv_obj_t * ui_lblEqHPFValue;
extern lv_obj_t * ui_contSliderEqWarm;
extern lv_obj_t * ui_lblEqWarmName;
extern lv_obj_t * ui_sliderEqWarmth;
extern lv_obj_t * ui_lblEqWarmValue;
extern lv_obj_t * ui_contSliderEqMud;
extern lv_obj_t * ui_lblEqMudName;
extern lv_obj_t * ui_sliderEqMud;
extern lv_obj_t * ui_lblEqMudValue;
extern lv_obj_t * ui_contSliderEqMid;
extern lv_obj_t * ui_lblEqMidName;
extern lv_obj_t * ui_sliderEqMid;
extern lv_obj_t * ui_lblEqMidValue;
extern lv_obj_t * ui_contSliderEqPres;
extern lv_obj_t * ui_lblEqPresName;
extern lv_obj_t * ui_sliderEqPres;
extern lv_obj_t * ui_lblEqPresValue;
extern lv_obj_t * ui_contSliderEqAir;
extern lv_obj_t * ui_lblEqAirName;
extern lv_obj_t * ui_sliderEqAir;
extern lv_obj_t * ui_lblEqAirValue;
extern lv_obj_t * ui_pnlSettings;
extern lv_obj_t * ui_SetupHeaderBar;
extern lv_obj_t * ui_btnBackSetup;
extern lv_obj_t * ui_ImageBtnBackSetup;
extern lv_obj_t * ui_btnNetworkSettings;
extern lv_obj_t * ui_imgSettings;
extern lv_obj_t * ui_contSliders;
extern lv_obj_t * ui_contInputSliderPeaksGrp;
extern lv_obj_t * ui_peakMeterInput;
extern lv_obj_t * ui_contSliderInputGain;
extern lv_obj_t * ui_lblGlobalInputGainName;
extern lv_obj_t * ui_sliderGlobalInputGain;
extern lv_obj_t * ui_lblGlobalInputGainValue;
extern lv_obj_t * ui_contOutputSliderPeaksGrp;
extern lv_obj_t * ui_peakMeterOutput;
extern lv_obj_t * ui_contSliderGlobalOutputVol;
extern lv_obj_t * ui_lblGlobalOutputVolName;
extern lv_obj_t * ui_sliderGlobalOutputVol;
extern lv_obj_t * ui_lblGlobalOutputVolValue;
extern lv_obj_t * ui_pnlNetworkSetup;
extern lv_obj_t * ui_lblWifiStatus;
extern lv_obj_t * ui_netConnect;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_SetupWiFiHeaderBar;
extern lv_obj_t * ui_btnWifiScan;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_listWifi;
extern lv_obj_t * ui_btnWifiConnect;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_btnNetworkSetupClose;
extern lv_obj_t * ui_lblNetworkSetupClose;
extern lv_obj_t * ui_kbPassword;
extern lv_obj_t * ui_taWifiPass;
extern lv_obj_t * ui_pwKB;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

