// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#include "../ui.h"

lv_obj_t * ui_ScreenMain = NULL;
lv_obj_t * ui_contHeader = NULL;
lv_obj_t * ui_contStatus = NULL;
lv_obj_t * ui_contLeftHdr = NULL;
lv_obj_t * ui_contCPU = NULL;
lv_obj_t * ui_lblCpu = NULL;
lv_obj_t * ui_lblCPUPercent = NULL;
lv_obj_t * ui_barCPU = NULL;
lv_obj_t * ui_contDSP = NULL;
lv_obj_t * ui_lblDSP = NULL;
lv_obj_t * ui_lblDSPPercent = NULL;
lv_obj_t * ui_barDSP = NULL;
lv_obj_t * ui_contCenterHdr = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_contRightHdr = NULL;
lv_obj_t * ui_imgUSB = NULL;
lv_obj_t * ui_imgBlueTooth = NULL;
lv_obj_t * ui_imgMQTT = NULL;
lv_obj_t * ui_imgWiFi = NULL;
lv_obj_t * ui_imgMic = NULL;
lv_obj_t * ui_contMeters = NULL;
lv_obj_t * ui_contMeterInput = NULL;
lv_obj_t * ui_contInputMeter = NULL;
lv_obj_t * ui_lblMetersInput = NULL;
lv_obj_t * ui_lblMetersInput1 = NULL;
lv_obj_t * ui_barInput = NULL;
lv_obj_t * ui_contEQ = NULL;
lv_obj_t * ui_contEQGraph = NULL;
lv_obj_t * ui_contEQGrid = NULL;
lv_obj_t * ui_gridGrp80 = NULL;
lv_obj_t * ui_grid80 = NULL;
lv_obj_t * ui_lbl80 = NULL;
lv_obj_t * ui_gridGrp160 = NULL;
lv_obj_t * ui_grid160 = NULL;
lv_obj_t * ui_lbl160 = NULL;
lv_obj_t * ui_gridGrp315 = NULL;
lv_obj_t * ui_grid315 = NULL;
lv_obj_t * ui_lbl315 = NULL;
lv_obj_t * ui_gridGrp630 = NULL;
lv_obj_t * ui_grid630 = NULL;
lv_obj_t * ui_lbl630 = NULL;
lv_obj_t * ui_gridGrp1K = NULL;
lv_obj_t * ui_grid1K = NULL;
lv_obj_t * ui_lbl1K = NULL;
lv_obj_t * ui_gridGrp2K5 = NULL;
lv_obj_t * ui_grid2K5 = NULL;
lv_obj_t * ui_lbl2K5 = NULL;
lv_obj_t * ui_gridGrp5K = NULL;
lv_obj_t * ui_grid5K = NULL;
lv_obj_t * ui_lbl5K = NULL;
lv_obj_t * ui_gridGrp10K = NULL;
lv_obj_t * ui_grid10K = NULL;
lv_obj_t * ui_lbl10K = NULL;
lv_obj_t * ui_graphEQ = NULL;
lv_obj_t * ui_graphEQ_Xaxis = NULL;
lv_obj_t * ui_graphEQ_Yaxis1 = NULL;
lv_obj_t * ui_graphEQ_Yaxis2 = NULL;
lv_obj_t * ui_contMeterOutput = NULL;
lv_obj_t * ui_contOutputMeter = NULL;
lv_obj_t * ui_lblMetersInput2 = NULL;
lv_obj_t * ui_lblMetersInput3 = NULL;
lv_obj_t * ui_barOutput = NULL;
lv_obj_t * ui_contControls = NULL;
lv_obj_t * ui_contHPF = NULL;
lv_obj_t * ui_lblControlsHPF = NULL;
lv_obj_t * ui_lblControlsHPF2 = NULL;
lv_obj_t * ui_contWarm = NULL;
lv_obj_t * ui_lblControlsWarm = NULL;
lv_obj_t * ui_lblControlsWarm1 = NULL;
lv_obj_t * ui_contPresence = NULL;
lv_obj_t * ui_lblControlsPres = NULL;
lv_obj_t * ui_lblControlsPres1 = NULL;
lv_obj_t * ui_contAir = NULL;
lv_obj_t * ui_lblControlsAir = NULL;
lv_obj_t * ui_lblControlsAir1 = NULL;
lv_obj_t * ui_contFooter = NULL;
lv_obj_t * ui_contFootorClick = NULL;
lv_obj_t * ui_lblSettings = NULL;
// event funtions

// build funtions

void ui_ScreenMain_screen_init(void)
{
    ui_ScreenMain = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenMain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ScreenMain, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_flex_flow(ui_ScreenMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenMain, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenMain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHeader = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_contHeader);
    lv_obj_set_height(ui_contHeader, 40);
    lv_obj_set_width(ui_contHeader, lv_pct(100));
    lv_obj_set_x(ui_contHeader, 77);
    lv_obj_set_y(ui_contHeader, -13);
    lv_obj_set_align(ui_contHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contHeader, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contHeader, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_contHeader, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contHeader, lv_color_hex(0x121212), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contHeader, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contHeader, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contHeader, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contHeader, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_contStatus = lv_obj_create(ui_contHeader);
    lv_obj_remove_style_all(ui_contStatus);
    lv_obj_set_width(ui_contStatus, lv_pct(100));
    lv_obj_set_height(ui_contStatus, lv_pct(100));
    lv_obj_set_x(ui_contStatus, 0);
    lv_obj_set_y(ui_contStatus, -1);
    lv_obj_set_align(ui_contStatus, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contStatus, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contStatus, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_contStatus, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_contStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contStatus, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contLeftHdr = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contLeftHdr);
    lv_obj_set_height(ui_contLeftHdr, 33);
    lv_obj_set_width(ui_contLeftHdr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_contLeftHdr, -139);
    lv_obj_set_y(ui_contLeftHdr, 18);
    lv_obj_set_align(ui_contLeftHdr, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_contLeftHdr, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contLeftHdr, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contLeftHdr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contLeftHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contLeftHdr, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contCPU = lv_obj_create(ui_contLeftHdr);
    lv_obj_remove_style_all(ui_contCPU);
    lv_obj_set_width(ui_contCPU, 126);
    lv_obj_set_height(ui_contCPU, 17);
    lv_obj_set_x(ui_contCPU, 55);
    lv_obj_set_y(ui_contCPU, 5);
    lv_obj_set_align(ui_contCPU, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contCPU, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contCPU, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contCPU, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contCPU, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contCPU, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCpu = lv_label_create(ui_contCPU);
    lv_obj_set_width(ui_lblCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblCpu, 69);
    lv_obj_set_y(ui_lblCpu, 0);
    lv_obj_set_align(ui_lblCpu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCpu, "CPU");
    lv_obj_set_style_text_color(ui_lblCpu, lv_color_hex(0xB0B6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCpu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblCPUPercent = lv_label_create(ui_contCPU);
    lv_obj_set_width(ui_lblCPUPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblCPUPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblCPUPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblCPUPercent, "37%");
    lv_obj_set_style_text_color(ui_lblCPUPercent, lv_color_hex(0xB0B6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblCPUPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barCPU = lv_bar_create(ui_contCPU);
    lv_bar_set_value(ui_barCPU, 37, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barCPU, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barCPU, 58);
    lv_obj_set_height(ui_barCPU, 8);
    lv_obj_set_x(ui_barCPU, 0);
    lv_obj_set_y(ui_barCPU, 7);
    lv_obj_set_align(ui_barCPU, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barCPU, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barCPU, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barCPU, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barCPU, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barCPU, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barCPU, lv_color_hex(0x00FF66), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barCPU, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_barCPU, lv_color_hex(0x00FF66), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_barCPU, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_barCPU, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_barCPU, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barCPU, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barCPU,
                                                                                             lv_obj_get_style_pad_right(ui_barCPU, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_contDSP = lv_obj_create(ui_contLeftHdr);
    lv_obj_remove_style_all(ui_contDSP);
    lv_obj_set_width(ui_contDSP, 126);
    lv_obj_set_height(ui_contDSP, 17);
    lv_obj_set_x(ui_contDSP, 55);
    lv_obj_set_y(ui_contDSP, 5);
    lv_obj_set_align(ui_contDSP, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contDSP, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contDSP, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contDSP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contDSP, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDSP = lv_label_create(ui_contDSP);
    lv_obj_set_width(ui_lblDSP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDSP, 69);
    lv_obj_set_y(ui_lblDSP, 0);
    lv_obj_set_align(ui_lblDSP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDSP, "DSP");
    lv_obj_set_style_text_color(ui_lblDSP, lv_color_hex(0xB0B6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblDSPPercent = lv_label_create(ui_contDSP);
    lv_obj_set_width(ui_lblDSPPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblDSPPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblDSPPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDSPPercent, "25%");
    lv_obj_set_style_text_color(ui_lblDSPPercent, lv_color_hex(0xB0B6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDSPPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barDSP = lv_bar_create(ui_contDSP);
    lv_bar_set_value(ui_barDSP, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barDSP, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barDSP, 58);
    lv_obj_set_height(ui_barDSP, 8);
    lv_obj_set_x(ui_barDSP, 0);
    lv_obj_set_y(ui_barDSP, 7);
    lv_obj_set_align(ui_barDSP, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barDSP, lv_color_hex(0x181818), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barDSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barDSP, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barDSP, lv_color_hex(0x00FF66), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barDSP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_barDSP, lv_color_hex(0x00FF66), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_barDSP, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_barDSP, 3, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_barDSP, 1, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barDSP, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barDSP,
                                                                                             lv_obj_get_style_pad_right(ui_barDSP, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_contCenterHdr = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contCenterHdr);
    lv_obj_set_width(ui_contCenterHdr, lv_pct(45));
    lv_obj_set_height(ui_contCenterHdr, lv_pct(100));
    lv_obj_set_x(ui_contCenterHdr, 192);
    lv_obj_set_y(ui_contCenterHdr, -10);
    lv_obj_set_align(ui_contCenterHdr, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contCenterHdr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contCenterHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contCenterHdr, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_contCenterHdr);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 28);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Vocal Preamp");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xB0B6BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contRightHdr = lv_obj_create(ui_contStatus);
    lv_obj_remove_style_all(ui_contRightHdr);
    lv_obj_set_width(ui_contRightHdr, 181);
    lv_obj_set_height(ui_contRightHdr, 50);
    lv_obj_set_x(ui_contRightHdr, 159);
    lv_obj_set_y(ui_contRightHdr, -9);
    lv_obj_set_align(ui_contRightHdr, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contRightHdr, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contRightHdr, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contRightHdr, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_contRightHdr, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contRightHdr, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgUSB = lv_image_create(ui_contRightHdr);
    lv_image_set_src(ui_imgUSB, &ui_img_icn_usb_png);
    lv_obj_set_width(ui_imgUSB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgUSB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgUSB, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgUSB, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgUSB, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgBlueTooth = lv_image_create(ui_contRightHdr);
    lv_image_set_src(ui_imgBlueTooth, &ui_img_bluetooth_ico_png);
    lv_obj_set_width(ui_imgBlueTooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgBlueTooth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgBlueTooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBlueTooth, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgBlueTooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMQTT = lv_image_create(ui_contRightHdr);
    lv_image_set_src(ui_imgMQTT, &ui_img_mqtt_svrstack_png);
    lv_obj_set_width(ui_imgMQTT, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMQTT, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMQTT, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMQTT, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMQTT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgWiFi = lv_image_create(ui_contRightHdr);
    lv_image_set_src(ui_imgWiFi, &ui_img_icn_wifi_png);
    lv_obj_set_width(ui_imgWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgWiFi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgMic = lv_image_create(ui_contRightHdr);
    lv_image_set_src(ui_imgMic, &ui_img_mic_ico_png);
    lv_obj_set_width(ui_imgMic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgMic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgMic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgMic, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgMic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contMeters = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_contMeters);
    lv_obj_set_height(ui_contMeters, 150);
    lv_obj_set_width(ui_contMeters, lv_pct(100));
    lv_obj_set_x(ui_contMeters, 100);
    lv_obj_set_y(ui_contMeters, 31);
    lv_obj_set_align(ui_contMeters, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMeters, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMeters, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contMeters, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contMeters, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contMeters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contMeters, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contMeters, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contMeters, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contMeters, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contMeters, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contMeters, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_contMeters, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contMeters, lv_color_hex(0xFFFFFF), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contMeters, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contMeters, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contMeters, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contMeters, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_contMeterInput = lv_obj_create(ui_contMeters);
    lv_obj_remove_style_all(ui_contMeterInput);
    lv_obj_set_width(ui_contMeterInput, lv_pct(20));
    lv_obj_set_height(ui_contMeterInput, lv_pct(100));
    lv_obj_set_align(ui_contMeterInput, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMeterInput, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMeterInput, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMeterInput, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contMeterInput, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contMeterInput, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contMeterInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contMeterInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contInputMeter = lv_obj_create(ui_contMeterInput);
    lv_obj_remove_style_all(ui_contInputMeter);
    lv_obj_set_width(ui_contInputMeter, 55);
    lv_obj_set_height(ui_contInputMeter, lv_pct(17));
    lv_obj_set_align(ui_contInputMeter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contInputMeter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contInputMeter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_contInputMeter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMetersInput = lv_label_create(ui_contInputMeter);
    lv_obj_set_width(ui_lblMetersInput, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMetersInput, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMetersInput, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMetersInput, "INPUT");
    lv_obj_set_style_text_color(ui_lblMetersInput, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMetersInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMetersInput, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMetersInput1 = lv_label_create(ui_contInputMeter);
    lv_obj_set_width(ui_lblMetersInput1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMetersInput1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMetersInput1, 1);
    lv_obj_set_y(ui_lblMetersInput1, -9);
    lv_obj_set_align(ui_lblMetersInput1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMetersInput1, "-18 dB");
    lv_obj_set_style_text_color(ui_lblMetersInput1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMetersInput1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMetersInput1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barInput = lv_bar_create(ui_contMeterInput);
    lv_bar_set_value(ui_barInput, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barInput, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barInput, 10);
    lv_obj_set_height(ui_barInput, 99);
    lv_obj_set_align(ui_barInput, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_barInput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barInput, lv_color_hex(0x081A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barInput, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barInput, lv_color_hex(0x081A14), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barInput, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_barInput, &ui_img_indicator_ver_25seg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barInput, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barInput,
                                                                                               lv_obj_get_style_pad_right(ui_barInput, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_contEQ = lv_obj_create(ui_contMeters);
    lv_obj_remove_style_all(ui_contEQ);
    lv_obj_set_width(ui_contEQ, lv_pct(53));
    lv_obj_set_height(ui_contEQ, lv_pct(100));
    lv_obj_set_align(ui_contEQ, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contEQ, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contEQ, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contEQ, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contEQ, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contEQ, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contEQ, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contEQ, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contEQ, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contEQGraph = lv_obj_create(ui_contEQ);
    lv_obj_remove_style_all(ui_contEQGraph);
    lv_obj_set_width(ui_contEQGraph, lv_pct(100));
    lv_obj_set_height(ui_contEQGraph, lv_pct(100));
    lv_obj_set_align(ui_contEQGraph, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contEQGraph, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contEQGraph, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contEQGraph, lv_color_hex(0x081A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contEQGraph, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_contEQGraph, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contEQGraph, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contEQGraph, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contEQGraph, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contEQGraph, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contEQGrid = lv_obj_create(ui_contEQGraph);
    lv_obj_remove_style_all(ui_contEQGrid);
    lv_obj_set_width(ui_contEQGrid, lv_pct(100));
    lv_obj_set_height(ui_contEQGrid, lv_pct(100));
    lv_obj_set_align(ui_contEQGrid, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contEQGrid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contEQGrid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contEQGrid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp80 = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp80);
    lv_obj_set_width(ui_gridGrp80, 20);
    lv_obj_set_height(ui_gridGrp80, lv_pct(100));
    lv_obj_set_x(ui_gridGrp80, -98);
    lv_obj_set_y(ui_gridGrp80, -2);
    lv_obj_set_align(ui_gridGrp80, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp80, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp80, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp80, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid80 = lv_obj_create(ui_gridGrp80);
    lv_obj_remove_style_all(ui_grid80);
    lv_obj_set_width(ui_grid80, 2);
    lv_obj_set_height(ui_grid80, lv_pct(93));
    lv_obj_set_x(ui_grid80, 18);
    lv_obj_set_y(ui_grid80, -1);
    lv_obj_set_align(ui_grid80, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_grid80, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid80, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid80, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_grid80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_grid80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl80 = lv_label_create(ui_gridGrp80);
    lv_obj_set_width(ui_lbl80, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl80, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl80, -75);
    lv_obj_set_y(ui_lbl80, 46);
    lv_obj_set_align(ui_lbl80, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lbl80, "80");
    lv_obj_set_style_text_color(ui_lbl80, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl80, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl80, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_lbl80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_lbl80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_lbl80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_lbl80, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp160 = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp160);
    lv_obj_set_width(ui_gridGrp160, 20);
    lv_obj_set_height(ui_gridGrp160, lv_pct(100));
    lv_obj_set_x(ui_gridGrp160, -75);
    lv_obj_set_y(ui_gridGrp160, -2);
    lv_obj_set_align(ui_gridGrp160, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp160, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp160, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp160, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid160 = lv_obj_create(ui_gridGrp160);
    lv_obj_remove_style_all(ui_grid160);
    lv_obj_set_width(ui_grid160, 2);
    lv_obj_set_height(ui_grid160, lv_pct(100));
    lv_obj_set_x(ui_grid160, 48);
    lv_obj_set_y(ui_grid160, -1);
    lv_obj_set_align(ui_grid160, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid160, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid160, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid160, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid160, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl160 = lv_label_create(ui_gridGrp160);
    lv_obj_set_width(ui_lbl160, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl160, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl160, -63);
    lv_obj_set_y(ui_lbl160, 54);
    lv_obj_set_align(ui_lbl160, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl160, "160");
    lv_obj_set_style_text_color(ui_lbl160, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl160, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl160, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp315 = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp315);
    lv_obj_set_width(ui_gridGrp315, 20);
    lv_obj_set_height(ui_gridGrp315, lv_pct(100));
    lv_obj_set_x(ui_gridGrp315, -46);
    lv_obj_set_y(ui_gridGrp315, -2);
    lv_obj_set_align(ui_gridGrp315, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp315, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp315, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp315, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid315 = lv_obj_create(ui_gridGrp315);
    lv_obj_remove_style_all(ui_grid315);
    lv_obj_set_width(ui_grid315, 2);
    lv_obj_set_height(ui_grid315, lv_pct(100));
    lv_obj_set_x(ui_grid315, 85);
    lv_obj_set_y(ui_grid315, 1);
    lv_obj_set_align(ui_grid315, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid315, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid315, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid315, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid315, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl315 = lv_label_create(ui_gridGrp315);
    lv_obj_set_width(ui_lbl315, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl315, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl315, -26);
    lv_obj_set_y(ui_lbl315, 54);
    lv_obj_set_align(ui_lbl315, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl315, "315");
    lv_obj_set_style_text_color(ui_lbl315, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl315, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl315, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp630 = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp630);
    lv_obj_set_width(ui_gridGrp630, 20);
    lv_obj_set_height(ui_gridGrp630, lv_pct(100));
    lv_obj_set_x(ui_gridGrp630, -19);
    lv_obj_set_y(ui_gridGrp630, -2);
    lv_obj_set_align(ui_gridGrp630, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp630, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp630, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp630, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid630 = lv_obj_create(ui_gridGrp630);
    lv_obj_remove_style_all(ui_grid630);
    lv_obj_set_width(ui_grid630, 2);
    lv_obj_set_height(ui_grid630, lv_pct(100));
    lv_obj_set_x(ui_grid630, 114);
    lv_obj_set_y(ui_grid630, 1);
    lv_obj_set_align(ui_grid630, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid630, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid630, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid630, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid630, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl630 = lv_label_create(ui_gridGrp630);
    lv_obj_set_width(ui_lbl630, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl630, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl630, 3);
    lv_obj_set_y(ui_lbl630, 54);
    lv_obj_set_align(ui_lbl630, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl630, "630");
    lv_obj_set_style_text_color(ui_lbl630, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl630, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl630, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp1K = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp1K);
    lv_obj_set_width(ui_gridGrp1K, 20);
    lv_obj_set_height(ui_gridGrp1K, lv_pct(100));
    lv_obj_set_x(ui_gridGrp1K, 8);
    lv_obj_set_y(ui_gridGrp1K, -2);
    lv_obj_set_align(ui_gridGrp1K, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp1K, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp1K, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp1K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid1K = lv_obj_create(ui_gridGrp1K);
    lv_obj_remove_style_all(ui_grid1K);
    lv_obj_set_width(ui_grid1K, 2);
    lv_obj_set_height(ui_grid1K, lv_pct(100));
    lv_obj_set_x(ui_grid1K, 145);
    lv_obj_set_y(ui_grid1K, -5);
    lv_obj_set_align(ui_grid1K, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid1K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid1K, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid1K, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid1K, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl1K = lv_label_create(ui_gridGrp1K);
    lv_obj_set_width(ui_lbl1K, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl1K, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl1K, 35);
    lv_obj_set_y(ui_lbl1K, 54);
    lv_obj_set_align(ui_lbl1K, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl1K, "1K");
    lv_obj_set_style_text_color(ui_lbl1K, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl1K, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl1K, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp2K5 = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp2K5);
    lv_obj_set_width(ui_gridGrp2K5, 20);
    lv_obj_set_height(ui_gridGrp2K5, lv_pct(100));
    lv_obj_set_x(ui_gridGrp2K5, 33);
    lv_obj_set_y(ui_gridGrp2K5, -2);
    lv_obj_set_align(ui_gridGrp2K5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp2K5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp2K5, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp2K5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid2K5 = lv_obj_create(ui_gridGrp2K5);
    lv_obj_remove_style_all(ui_grid2K5);
    lv_obj_set_width(ui_grid2K5, 2);
    lv_obj_set_height(ui_grid2K5, lv_pct(100));
    lv_obj_set_x(ui_grid2K5, 170);
    lv_obj_set_y(ui_grid2K5, -4);
    lv_obj_set_align(ui_grid2K5, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid2K5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid2K5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid2K5, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid2K5, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl2K5 = lv_label_create(ui_gridGrp2K5);
    lv_obj_set_width(ui_lbl2K5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl2K5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl2K5, 56);
    lv_obj_set_y(ui_lbl2K5, 54);
    lv_obj_set_align(ui_lbl2K5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl2K5, "2.5K");
    lv_obj_set_style_text_color(ui_lbl2K5, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl2K5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl2K5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp5K = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp5K);
    lv_obj_set_width(ui_gridGrp5K, 20);
    lv_obj_set_height(ui_gridGrp5K, lv_pct(100));
    lv_obj_set_x(ui_gridGrp5K, 51);
    lv_obj_set_y(ui_gridGrp5K, -2);
    lv_obj_set_align(ui_gridGrp5K, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp5K, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp5K, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp5K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid5K = lv_obj_create(ui_gridGrp5K);
    lv_obj_remove_style_all(ui_grid5K);
    lv_obj_set_width(ui_grid5K, 2);
    lv_obj_set_height(ui_grid5K, lv_pct(100));
    lv_obj_set_x(ui_grid5K, 189);
    lv_obj_set_y(ui_grid5K, -4);
    lv_obj_set_align(ui_grid5K, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid5K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid5K, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid5K, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid5K, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl5K = lv_label_create(ui_gridGrp5K);
    lv_obj_set_width(ui_lbl5K, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl5K, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl5K, 79);
    lv_obj_set_y(ui_lbl5K, 54);
    lv_obj_set_align(ui_lbl5K, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl5K, "5K");
    lv_obj_set_style_text_color(ui_lbl5K, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl5K, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl5K, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_gridGrp10K = lv_obj_create(ui_contEQGrid);
    lv_obj_remove_style_all(ui_gridGrp10K);
    lv_obj_set_width(ui_gridGrp10K, 20);
    lv_obj_set_height(ui_gridGrp10K, lv_pct(100));
    lv_obj_set_x(ui_gridGrp10K, 95);
    lv_obj_set_y(ui_gridGrp10K, -2);
    lv_obj_set_align(ui_gridGrp10K, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_gridGrp10K, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_gridGrp10K, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_gridGrp10K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_grid10K = lv_obj_create(ui_gridGrp10K);
    lv_obj_remove_style_all(ui_grid10K);
    lv_obj_set_width(ui_grid10K, 2);
    lv_obj_set_height(ui_grid10K, lv_pct(100));
    lv_obj_set_x(ui_grid10K, 213);
    lv_obj_set_y(ui_grid10K, -4);
    lv_obj_set_align(ui_grid10K, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_grid10K, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_grid10K, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_grid10K, lv_color_hex(0x1E4A3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_grid10K, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lbl10K = lv_label_create(ui_gridGrp10K);
    lv_obj_set_width(ui_lbl10K, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbl10K, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbl10K, 101);
    lv_obj_set_y(ui_lbl10K, 54);
    lv_obj_set_align(ui_lbl10K, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbl10K, "10K");
    lv_obj_set_style_text_color(ui_lbl10K, lv_color_hex(0x5CF2C0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lbl10K, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lbl10K, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphEQ = lv_chart_create(ui_contEQGraph);
    lv_obj_set_width(ui_graphEQ, lv_pct(100));
    lv_obj_set_height(ui_graphEQ, lv_pct(100));
    lv_obj_set_align(ui_graphEQ, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_graphEQ, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_graphEQ, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_graphEQ, LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_graphEQ, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_graphEQ, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_graphEQ, 32);
    lv_chart_set_div_line_count(ui_graphEQ, 0, 0);
    lv_obj_set_style_bg_color(ui_graphEQ, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_graphEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_graphEQ, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_graphEQ_Xaxis = lv_scale_create(ui_graphEQ);
    lv_scale_set_mode(ui_graphEQ_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_graphEQ_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_graphEQ_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_graphEQ_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_graphEQ,
                                                                    LV_PART_MAIN) + lv_obj_get_style_border_width(ui_graphEQ, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_graphEQ_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_graphEQ_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_graphEQ_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_graphEQ_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_graphEQ_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_graphEQ_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_graphEQ_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_graphEQ_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_graphEQ_Xaxis, false);
    ui_graphEQ_Yaxis1 = lv_scale_create(ui_graphEQ);
    lv_scale_set_mode(ui_graphEQ_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_graphEQ_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_graphEQ_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_graphEQ_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_graphEQ,
                                                                    LV_PART_MAIN) - lv_obj_get_style_border_width(ui_graphEQ, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_graphEQ_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_graphEQ_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_graphEQ_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_graphEQ_Yaxis1, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_graphEQ_Yaxis1, false);
    ui_graphEQ_Yaxis2 = lv_scale_create(ui_graphEQ);
    lv_scale_set_mode(ui_graphEQ_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_graphEQ_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_graphEQ_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_graphEQ_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_graphEQ,
                                                                    LV_PART_MAIN) + lv_obj_get_style_border_width(ui_graphEQ, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_graphEQ_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_graphEQ_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_graphEQ_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_graphEQ_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_graphEQ_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_graphEQ_Yaxis2, false);
    lv_chart_series_t * ui_graphEQ_series_1 = lv_chart_add_series(ui_graphEQ, lv_color_hex(0x5CF2C0),
                                                                  LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_graphEQ_series_1_array[] = { 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50 };
    lv_chart_set_ext_y_array(ui_graphEQ, ui_graphEQ_series_1, ui_graphEQ_series_1_array);

    lv_obj_set_style_line_color(ui_graphEQ, lv_color_hex(0x5CF2C0), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_graphEQ, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_width(ui_graphEQ, 3, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_line_rounded(ui_graphEQ, true, LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_graphEQ, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_graphEQ, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_graphEQ, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_graphEQ, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_contMeterOutput = lv_obj_create(ui_contMeters);
    lv_obj_remove_style_all(ui_contMeterOutput);
    lv_obj_set_width(ui_contMeterOutput, lv_pct(20));
    lv_obj_set_height(ui_contMeterOutput, lv_pct(100));
    lv_obj_set_align(ui_contMeterOutput, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contMeterOutput, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contMeterOutput, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contMeterOutput, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contMeterOutput, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contMeterOutput, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contMeterOutput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contMeterOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contOutputMeter = lv_obj_create(ui_contMeterOutput);
    lv_obj_remove_style_all(ui_contOutputMeter);
    lv_obj_set_width(ui_contOutputMeter, 55);
    lv_obj_set_height(ui_contOutputMeter, lv_pct(17));
    lv_obj_set_align(ui_contOutputMeter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contOutputMeter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contOutputMeter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_contOutputMeter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblMetersInput2 = lv_label_create(ui_contOutputMeter);
    lv_obj_set_width(ui_lblMetersInput2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMetersInput2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblMetersInput2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMetersInput2, "OUTPUT");
    lv_obj_set_style_text_color(ui_lblMetersInput2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMetersInput2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMetersInput2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMetersInput3 = lv_label_create(ui_contOutputMeter);
    lv_obj_set_width(ui_lblMetersInput3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMetersInput3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMetersInput3, 1);
    lv_obj_set_y(ui_lblMetersInput3, -9);
    lv_obj_set_align(ui_lblMetersInput3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMetersInput3, "-18 dB");
    lv_obj_set_style_text_color(ui_lblMetersInput3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMetersInput3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMetersInput3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barOutput = lv_bar_create(ui_contMeterOutput);
    lv_bar_set_value(ui_barOutput, 60, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_barOutput, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_barOutput, 10);
    lv_obj_set_height(ui_barOutput, 100);
    lv_obj_set_align(ui_barOutput, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_barOutput, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barOutput, lv_color_hex(0x081A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOutput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barOutput, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barOutput, lv_color_hex(0x081A14), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barOutput, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_barOutput, &ui_img_indicator_ver_25seg_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barOutput, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barOutput,
                                                                                                lv_obj_get_style_pad_right(ui_barOutput, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_contControls = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_contControls);
    lv_obj_set_height(ui_contControls, 62);
    lv_obj_set_width(ui_contControls, lv_pct(100));
    lv_obj_set_x(ui_contControls, 69);
    lv_obj_set_y(ui_contControls, 133);
    lv_obj_set_align(ui_contControls, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contControls, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contControls, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contControls, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contControls, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contControls, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contControls, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contControls, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contControls, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contControls, 6, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHPF = lv_obj_create(ui_contControls);
    lv_obj_remove_style_all(ui_contHPF);
    lv_obj_set_width(ui_contHPF, lv_pct(20));
    lv_obj_set_height(ui_contHPF, lv_pct(100));
    lv_obj_set_x(ui_contHPF, -181);
    lv_obj_set_y(ui_contHPF, 0);
    lv_obj_set_align(ui_contHPF, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contHPF, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contHPF, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contHPF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contHPF, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contHPF, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contHPF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contHPF, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contHPF, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contHPF, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contHPF, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contHPF, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsHPF = lv_label_create(ui_contHPF);
    lv_obj_set_width(ui_lblControlsHPF, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsHPF, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsHPF, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsHPF, "HPF");
    lv_obj_set_style_text_color(ui_lblControlsHPF, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsHPF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsHPF2 = lv_label_create(ui_contHPF);
    lv_obj_set_width(ui_lblControlsHPF2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsHPF2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsHPF2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsHPF2, "80Hz");
    lv_obj_set_style_text_color(ui_lblControlsHPF2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsHPF2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contWarm = lv_obj_create(ui_contControls);
    lv_obj_remove_style_all(ui_contWarm);
    lv_obj_set_width(ui_contWarm, lv_pct(20));
    lv_obj_set_height(ui_contWarm, lv_pct(100));
    lv_obj_set_x(ui_contWarm, -65);
    lv_obj_set_y(ui_contWarm, 0);
    lv_obj_set_align(ui_contWarm, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contWarm, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contWarm, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contWarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contWarm, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contWarm, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contWarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contWarm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contWarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contWarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contWarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contWarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsWarm = lv_label_create(ui_contWarm);
    lv_obj_set_width(ui_lblControlsWarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsWarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsWarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsWarm, "WARM");
    lv_obj_set_style_text_color(ui_lblControlsWarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsWarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsWarm1 = lv_label_create(ui_contWarm);
    lv_obj_set_width(ui_lblControlsWarm1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsWarm1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsWarm1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsWarm1, "+2dB");
    lv_obj_set_style_text_color(ui_lblControlsWarm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsWarm1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contPresence = lv_obj_create(ui_contControls);
    lv_obj_remove_style_all(ui_contPresence);
    lv_obj_set_width(ui_contPresence, lv_pct(22));
    lv_obj_set_height(ui_contPresence, lv_pct(100));
    lv_obj_set_x(ui_contPresence, 63);
    lv_obj_set_y(ui_contPresence, 0);
    lv_obj_set_align(ui_contPresence, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contPresence, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contPresence, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contPresence, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contPresence, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contPresence, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contPresence, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contPresence, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contPresence, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contPresence, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contPresence, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contPresence, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsPres = lv_label_create(ui_contPresence);
    lv_obj_set_width(ui_lblControlsPres, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsPres, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsPres, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsPres, "PRES");
    lv_obj_set_style_text_color(ui_lblControlsPres, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsPres, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsPres1 = lv_label_create(ui_contPresence);
    lv_obj_set_width(ui_lblControlsPres1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsPres1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsPres1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsPres1, "+3dB");
    lv_obj_set_style_text_color(ui_lblControlsPres1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsPres1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contAir = lv_obj_create(ui_contControls);
    lv_obj_remove_style_all(ui_contAir);
    lv_obj_set_width(ui_contAir, lv_pct(20));
    lv_obj_set_height(ui_contAir, lv_pct(100));
    lv_obj_set_x(ui_contAir, 182);
    lv_obj_set_y(ui_contAir, 0);
    lv_obj_set_align(ui_contAir, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contAir, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contAir, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contAir, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contAir, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contAir, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contAir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contAir, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contAir, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contAir, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contAir, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contAir, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsAir = lv_label_create(ui_contAir);
    lv_obj_set_width(ui_lblControlsAir, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsAir, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsAir, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsAir, "AIR");
    lv_obj_set_style_text_color(ui_lblControlsAir, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsAir, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblControlsAir1 = lv_label_create(ui_contAir);
    lv_obj_set_width(ui_lblControlsAir1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblControlsAir1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblControlsAir1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblControlsAir1, "+1dB");
    lv_obj_set_style_text_color(ui_lblControlsAir1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblControlsAir1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contFooter = lv_obj_create(ui_ScreenMain);
    lv_obj_remove_style_all(ui_contFooter);
    lv_obj_set_height(ui_contFooter, 68);
    lv_obj_set_width(ui_contFooter, lv_pct(100));
    lv_obj_set_x(ui_contFooter, 31);
    lv_obj_set_y(ui_contFooter, 116);
    lv_obj_set_align(ui_contFooter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contFooter, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contFooter, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contFootorClick = lv_obj_create(ui_contFooter);
    lv_obj_remove_style_all(ui_contFootorClick);
    lv_obj_set_width(ui_contFootorClick, lv_pct(96));
    lv_obj_set_height(ui_contFootorClick, lv_pct(77));
    lv_obj_set_x(ui_contFootorClick, 1);
    lv_obj_set_y(ui_contFootorClick, 3);
    lv_obj_set_align(ui_contFootorClick, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contFootorClick, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contFootorClick, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contFootorClick, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contFootorClick, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contFootorClick, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contFootorClick, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contFootorClick, lv_color_hex(0x3B7C5F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contFootorClick, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contFootorClick, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_contFootorClick, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_contFootorClick, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_contFootorClick, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contFootorClick, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contFootorClick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_contFootorClick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_contFootorClick, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contFootorClick, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contFootorClick, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSettings = lv_label_create(ui_contFootorClick);
    lv_obj_set_width(ui_lblSettings, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSettings, "GLOBAL SETTINGS");
    lv_obj_set_style_text_color(ui_lblSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenMain_screen_destroy(void)
{
    if(ui_ScreenMain) lv_obj_del(ui_ScreenMain);

    // NULL screen variables
    ui_ScreenMain = NULL;
    ui_contHeader = NULL;
    ui_contStatus = NULL;
    ui_contLeftHdr = NULL;
    ui_contCPU = NULL;
    ui_lblCpu = NULL;
    ui_lblCPUPercent = NULL;
    ui_barCPU = NULL;
    ui_contDSP = NULL;
    ui_lblDSP = NULL;
    ui_lblDSPPercent = NULL;
    ui_barDSP = NULL;
    ui_contCenterHdr = NULL;
    ui_Label3 = NULL;
    ui_contRightHdr = NULL;
    ui_imgUSB = NULL;
    ui_imgBlueTooth = NULL;
    ui_imgMQTT = NULL;
    ui_imgWiFi = NULL;
    ui_imgMic = NULL;
    ui_contMeters = NULL;
    ui_contMeterInput = NULL;
    ui_contInputMeter = NULL;
    ui_lblMetersInput = NULL;
    ui_lblMetersInput1 = NULL;
    ui_barInput = NULL;
    ui_contEQ = NULL;
    ui_contEQGraph = NULL;
    ui_contEQGrid = NULL;
    ui_gridGrp80 = NULL;
    ui_grid80 = NULL;
    ui_lbl80 = NULL;
    ui_gridGrp160 = NULL;
    ui_grid160 = NULL;
    ui_lbl160 = NULL;
    ui_gridGrp315 = NULL;
    ui_grid315 = NULL;
    ui_lbl315 = NULL;
    ui_gridGrp630 = NULL;
    ui_grid630 = NULL;
    ui_lbl630 = NULL;
    ui_gridGrp1K = NULL;
    ui_grid1K = NULL;
    ui_lbl1K = NULL;
    ui_gridGrp2K5 = NULL;
    ui_grid2K5 = NULL;
    ui_lbl2K5 = NULL;
    ui_gridGrp5K = NULL;
    ui_grid5K = NULL;
    ui_lbl5K = NULL;
    ui_gridGrp10K = NULL;
    ui_grid10K = NULL;
    ui_lbl10K = NULL;
    ui_graphEQ = NULL;
    ui_contMeterOutput = NULL;
    ui_contOutputMeter = NULL;
    ui_lblMetersInput2 = NULL;
    ui_lblMetersInput3 = NULL;
    ui_barOutput = NULL;
    ui_contControls = NULL;
    ui_contHPF = NULL;
    ui_lblControlsHPF = NULL;
    ui_lblControlsHPF2 = NULL;
    ui_contWarm = NULL;
    ui_lblControlsWarm = NULL;
    ui_lblControlsWarm1 = NULL;
    ui_contPresence = NULL;
    ui_lblControlsPres = NULL;
    ui_lblControlsPres1 = NULL;
    ui_contAir = NULL;
    ui_lblControlsAir = NULL;
    ui_lblControlsAir1 = NULL;
    ui_contFooter = NULL;
    ui_contFootorClick = NULL;
    ui_lblSettings = NULL;

}
