// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#include "../ui.h"

lv_obj_t * ui_ScreenAudioDSP = NULL;
lv_obj_t * ui_contAudioDSPHeader = NULL;
lv_obj_t * ui_btnBackAudioDSP = NULL;
lv_obj_t * ui_imgBackArrow5 = NULL;
lv_obj_t * ui_lblAudioDSP = NULL;
lv_obj_t * ui_contHeaderSpacer5 = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_swCompEnable = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_swNoiseGateEnable = NULL;
// event funtions

// build funtions

void ui_ScreenAudioDSP_screen_init(void)
{
    ui_ScreenAudioDSP = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenAudioDSP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenAudioDSP, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenAudioDSP, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenAudioDSP, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenAudioDSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ScreenAudioDSP, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ScreenAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contAudioDSPHeader = lv_obj_create(ui_ScreenAudioDSP);
    lv_obj_remove_style_all(ui_contAudioDSPHeader);
    lv_obj_set_height(ui_contAudioDSPHeader, 60);
    lv_obj_set_width(ui_contAudioDSPHeader, lv_pct(100));
    lv_obj_set_x(ui_contAudioDSPHeader, 1);
    lv_obj_set_y(ui_contAudioDSPHeader, -133);
    lv_obj_set_align(ui_contAudioDSPHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_contAudioDSPHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contAudioDSPHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contAudioDSPHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contAudioDSPHeader, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contAudioDSPHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackAudioDSP = lv_button_create(ui_contAudioDSPHeader);
    lv_obj_set_width(ui_btnBackAudioDSP, 80);
    lv_obj_set_height(ui_btnBackAudioDSP, lv_pct(100));
    lv_obj_set_x(ui_btnBackAudioDSP, -196);
    lv_obj_set_y(ui_btnBackAudioDSP, 1);
    lv_obj_set_align(ui_btnBackAudioDSP, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_btnBackAudioDSP, 10);
    lv_obj_add_flag(ui_btnBackAudioDSP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackAudioDSP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackAudioDSP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackAudioDSP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackAudioDSP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBackArrow5 = lv_image_create(ui_btnBackAudioDSP);
    lv_image_set_src(ui_imgBackArrow5, &ui_img_icn_back_png);
    lv_obj_set_width(ui_imgBackArrow5, lv_pct(100));
    lv_obj_set_height(ui_imgBackArrow5, lv_pct(100));
    lv_obj_set_align(ui_imgBackArrow5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBackArrow5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgBackArrow5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblAudioDSP = lv_label_create(ui_contAudioDSPHeader);
    lv_obj_set_width(ui_lblAudioDSP, lv_pct(68));
    lv_obj_set_height(ui_lblAudioDSP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblAudioDSP, 4);
    lv_obj_set_y(ui_lblAudioDSP, 0);
    lv_obj_set_align(ui_lblAudioDSP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblAudioDSP, "AUDIO");
    lv_obj_set_style_text_color(ui_lblAudioDSP, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblAudioDSP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblAudioDSP, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblAudioDSP, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHeaderSpacer5 = lv_obj_create(ui_contAudioDSPHeader);
    lv_obj_remove_style_all(ui_contHeaderSpacer5);
    lv_obj_set_height(ui_contHeaderSpacer5, lv_pct(100));
    lv_obj_set_flex_grow(ui_contHeaderSpacer5, 1);
    lv_obj_set_x(ui_contHeaderSpacer5, 10);
    lv_obj_set_y(ui_contHeaderSpacer5, -17);
    lv_obj_set_align(ui_contHeaderSpacer5, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_contHeaderSpacer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container15 = lv_obj_create(ui_ScreenAudioDSP);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_height(ui_Container15, 36);
    lv_obj_set_width(ui_Container15, lv_pct(50));
    lv_obj_set_x(ui_Container15, 79);
    lv_obj_set_y(ui_Container15, 11);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container15, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container15, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container15, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Container15);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -124);
    lv_obj_set_y(ui_Label16, -51);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Compression");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swCompEnable = lv_switch_create(ui_Container15);
    lv_obj_set_width(ui_swCompEnable, 65);
    lv_obj_set_height(ui_swCompEnable, lv_pct(75));
    lv_obj_set_x(ui_swCompEnable, -64);
    lv_obj_set_y(ui_swCompEnable, -51);
    lv_obj_set_align(ui_swCompEnable, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swCompEnable, lv_color_hex(0x12EF31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swCompEnable, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swCompEnable, lv_color_hex(0x12EF31), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swCompEnable, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swCompEnable, lv_color_hex(0x082418), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swCompEnable, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_ScreenAudioDSP);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_height(ui_Container16, 36);
    lv_obj_set_width(ui_Container16, lv_pct(50));
    lv_obj_set_x(ui_Container16, 72);
    lv_obj_set_y(ui_Container16, 18);
    lv_obj_set_align(ui_Container16, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container16, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container16, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Container16);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -144);
    lv_obj_set_y(ui_Label17, -97);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Noise Gate");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_swNoiseGateEnable = lv_switch_create(ui_Container16);
    lv_obj_set_width(ui_swNoiseGateEnable, 65);
    lv_obj_set_height(ui_swNoiseGateEnable, lv_pct(75));
    lv_obj_set_x(ui_swNoiseGateEnable, -67);
    lv_obj_set_y(ui_swNoiseGateEnable, -96);
    lv_obj_set_align(ui_swNoiseGateEnable, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_swNoiseGateEnable, lv_color_hex(0x12EF31), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swNoiseGateEnable, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swNoiseGateEnable, lv_color_hex(0x12EF31), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_swNoiseGateEnable, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(ui_swNoiseGateEnable, lv_color_hex(0x082418), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_swNoiseGateEnable, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_ScreenAudioDSP_screen_destroy(void)
{
    if(ui_ScreenAudioDSP) lv_obj_del(ui_ScreenAudioDSP);

    // NULL screen variables
    ui_ScreenAudioDSP = NULL;
    ui_contAudioDSPHeader = NULL;
    ui_btnBackAudioDSP = NULL;
    ui_imgBackArrow5 = NULL;
    ui_lblAudioDSP = NULL;
    ui_contHeaderSpacer5 = NULL;
    ui_Container15 = NULL;
    ui_Label16 = NULL;
    ui_swCompEnable = NULL;
    ui_Container16 = NULL;
    ui_Label17 = NULL;
    ui_swNoiseGateEnable = NULL;

}
