// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#include "../ui.h"

lv_obj_t * ui_ScreenGlobal = NULL;
lv_obj_t * ui_contGBLHeader = NULL;
lv_obj_t * ui_btnBackGBLSettings = NULL;
lv_obj_t * ui_imgBackArrow = NULL;
lv_obj_t * ui_lblGBLSettings = NULL;
lv_obj_t * ui_contHeaderSpacer = NULL;
lv_obj_t * ui_contGBLContent = NULL;
lv_obj_t * ui_contBtnAudio = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_contBtnWIFI = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_contBtnSystem = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Image9 = NULL;
// event funtions

// build funtions

void ui_ScreenGlobal_screen_init(void)
{
    ui_ScreenGlobal = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenGlobal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenGlobal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenGlobal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenGlobal, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenGlobal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ScreenGlobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ScreenGlobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ScreenGlobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ScreenGlobal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contGBLHeader = lv_obj_create(ui_ScreenGlobal);
    lv_obj_remove_style_all(ui_contGBLHeader);
    lv_obj_set_height(ui_contGBLHeader, 60);
    lv_obj_set_width(ui_contGBLHeader, lv_pct(100));
    lv_obj_set_x(ui_contGBLHeader, 1);
    lv_obj_set_y(ui_contGBLHeader, -133);
    lv_obj_set_align(ui_contGBLHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_contGBLHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contGBLHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contGBLHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contGBLHeader, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contGBLHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackGBLSettings = lv_button_create(ui_contGBLHeader);
    lv_obj_set_width(ui_btnBackGBLSettings, 80);
    lv_obj_set_height(ui_btnBackGBLSettings, lv_pct(100));
    lv_obj_set_x(ui_btnBackGBLSettings, -196);
    lv_obj_set_y(ui_btnBackGBLSettings, 1);
    lv_obj_set_align(ui_btnBackGBLSettings, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_btnBackGBLSettings, 10);
    lv_obj_add_flag(ui_btnBackGBLSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackGBLSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackGBLSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackGBLSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackGBLSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackGBLSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBackArrow = lv_image_create(ui_btnBackGBLSettings);
    lv_image_set_src(ui_imgBackArrow, &ui_img_icn_back_png);
    lv_obj_set_width(ui_imgBackArrow, lv_pct(100));
    lv_obj_set_height(ui_imgBackArrow, lv_pct(100));
    lv_obj_set_align(ui_imgBackArrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBackArrow, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgBackArrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblGBLSettings = lv_label_create(ui_contGBLHeader);
    lv_obj_set_width(ui_lblGBLSettings, lv_pct(68));
    lv_obj_set_height(ui_lblGBLSettings, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblGBLSettings, 4);
    lv_obj_set_y(ui_lblGBLSettings, 0);
    lv_obj_set_align(ui_lblGBLSettings, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblGBLSettings, "Global Settings");
    lv_obj_set_style_text_color(ui_lblGBLSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblGBLSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblGBLSettings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblGBLSettings, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHeaderSpacer = lv_obj_create(ui_contGBLHeader);
    lv_obj_remove_style_all(ui_contHeaderSpacer);
    lv_obj_set_height(ui_contHeaderSpacer, lv_pct(100));
    lv_obj_set_flex_grow(ui_contHeaderSpacer, 1);
    lv_obj_set_x(ui_contHeaderSpacer, 10);
    lv_obj_set_y(ui_contHeaderSpacer, -17);
    lv_obj_set_align(ui_contHeaderSpacer, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_contHeaderSpacer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contGBLContent = lv_obj_create(ui_ScreenGlobal);
    lv_obj_remove_style_all(ui_contGBLContent);
    lv_obj_set_width(ui_contGBLContent, lv_pct(100));
    lv_obj_set_flex_grow(ui_contGBLContent, 1);
    lv_obj_set_x(ui_contGBLContent, -3);
    lv_obj_set_y(ui_contGBLContent, -18);
    lv_obj_set_align(ui_contGBLContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contGBLContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contGBLContent, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contGBLContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contGBLContent, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contGBLContent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contGBLContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contGBLContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contGBLContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contGBLContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contGBLContent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contGBLContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contBtnAudio = lv_button_create(ui_contGBLContent);
    lv_obj_set_height(ui_contBtnAudio, 40);
    lv_obj_set_width(ui_contBtnAudio, lv_pct(100));
    lv_obj_set_align(ui_contBtnAudio, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contBtnAudio, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contBtnAudio, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_contBtnAudio, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_contBtnAudio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contBtnAudio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contBtnAudio, lv_color_hex(0x05170F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contBtnAudio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contBtnAudio, lv_color_hex(0x4B8D35), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contBtnAudio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contBtnAudio, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contBtnAudio, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contBtnAudio, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contBtnAudio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contBtnAudio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_contBtnAudio);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "AUDIO / DSP");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_contBtnAudio);
    lv_image_set_src(ui_Image1, &ui_img_icn_forward_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contBtnWIFI = lv_button_create(ui_contGBLContent);
    lv_obj_set_height(ui_contBtnWIFI, 40);
    lv_obj_set_width(ui_contBtnWIFI, lv_pct(100));
    lv_obj_set_align(ui_contBtnWIFI, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contBtnWIFI, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contBtnWIFI, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_contBtnWIFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_contBtnWIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contBtnWIFI, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contBtnWIFI, lv_color_hex(0x05170F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contBtnWIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contBtnWIFI, lv_color_hex(0x4B8D35), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contBtnWIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contBtnWIFI, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contBtnWIFI, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contBtnWIFI, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contBtnWIFI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contBtnWIFI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_contBtnWIFI);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "WIFI");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_contBtnWIFI);
    lv_image_set_src(ui_Image2, &ui_img_icn_forward_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contBtnSystem = lv_button_create(ui_contGBLContent);
    lv_obj_set_height(ui_contBtnSystem, 40);
    lv_obj_set_width(ui_contBtnSystem, lv_pct(100));
    lv_obj_set_align(ui_contBtnSystem, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contBtnSystem, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contBtnSystem, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_contBtnSystem, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_contBtnSystem, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_contBtnSystem, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_contBtnSystem, lv_color_hex(0x05170F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contBtnSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_contBtnSystem, lv_color_hex(0x4B8D35), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_contBtnSystem, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_contBtnSystem, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_contBtnSystem, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contBtnSystem, 14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contBtnSystem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contBtnSystem, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_contBtnSystem);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "SYSTEM");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_contBtnSystem);
    lv_image_set_src(ui_Image9, &ui_img_icn_forward_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_ScreenGlobal_screen_destroy(void)
{
    if(ui_ScreenGlobal) lv_obj_del(ui_ScreenGlobal);

    // NULL screen variables
    ui_ScreenGlobal = NULL;
    ui_contGBLHeader = NULL;
    ui_btnBackGBLSettings = NULL;
    ui_imgBackArrow = NULL;
    ui_lblGBLSettings = NULL;
    ui_contHeaderSpacer = NULL;
    ui_contGBLContent = NULL;
    ui_contBtnAudio = NULL;
    ui_Label1 = NULL;
    ui_Image1 = NULL;
    ui_contBtnWIFI = NULL;
    ui_Label2 = NULL;
    ui_Image2 = NULL;
    ui_contBtnSystem = NULL;
    ui_Label11 = NULL;
    ui_Image9 = NULL;

}
