// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef UI_SCREENSYSTEM_H
#define UI_SCREENSYSTEM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSystem
extern void ui_ScreenSystem_screen_init(void);
extern void ui_ScreenSystem_screen_destroy(void);
extern lv_obj_t * ui_ScreenSystem;
extern lv_obj_t * ui_contSystemHeader;
extern lv_obj_t * ui_btnBackSystem;
extern lv_obj_t * ui_imgBackArrow1;
extern lv_obj_t * ui_lblSystem;
extern lv_obj_t * ui_contHeaderSpacer1;
extern lv_obj_t * ui_contSystemContent;
extern lv_obj_t * ui_contBlueTooth;
extern lv_obj_t * ui_swBlueToothEnable;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_contBtnBTPair;
extern lv_obj_t * ui_lblDevName;
extern lv_obj_t * ui_btnBlueToothPair;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_contMQTT;
extern lv_obj_t * ui_swMQTTEnable;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_contBtnConnect;
extern lv_obj_t * ui_lblBrokerName;
extern lv_obj_t * ui_btnBlueToothPair1;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_contDevice;
extern lv_obj_t * ui_spacer2;
extern lv_obj_t * ui_btnRestart;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_btnFactoryReset;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

