// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef UI_SCREENMAIN_H
#define UI_SCREENMAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenMain
extern void ui_ScreenMain_screen_init(void);
extern void ui_ScreenMain_screen_destroy(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_contHeader;
extern lv_obj_t * ui_contStatus;
extern lv_obj_t * ui_contLeftHdr;
extern lv_obj_t * ui_contCPU;
extern lv_obj_t * ui_lblCpu;
extern lv_obj_t * ui_lblCPUPercent;
extern lv_obj_t * ui_barCPU;
extern lv_obj_t * ui_contDSP;
extern lv_obj_t * ui_lblDSP;
extern lv_obj_t * ui_lblDSPPercent;
extern lv_obj_t * ui_barDSP;
extern lv_obj_t * ui_contCenterHdr;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_contRightHdr;
extern lv_obj_t * ui_imgUSB;
extern lv_obj_t * ui_imgBlueTooth;
extern lv_obj_t * ui_imgMQTT;
extern lv_obj_t * ui_imgWiFi;
extern lv_obj_t * ui_imgMic;
extern lv_obj_t * ui_contMeters;
extern lv_obj_t * ui_contMeterInput;
extern lv_obj_t * ui_contInputMeter;
extern lv_obj_t * ui_lblMetersInput;
extern lv_obj_t * ui_lblMetersInput1;
extern lv_obj_t * ui_barInput;
extern lv_obj_t * ui_contEQ;
extern lv_obj_t * ui_contEQGraph;
extern lv_obj_t * ui_contEQGrid;
extern lv_obj_t * ui_gridGrp80;
extern lv_obj_t * ui_grid80;
extern lv_obj_t * ui_lbl80;
extern lv_obj_t * ui_gridGrp160;
extern lv_obj_t * ui_grid160;
extern lv_obj_t * ui_lbl160;
extern lv_obj_t * ui_gridGrp315;
extern lv_obj_t * ui_grid315;
extern lv_obj_t * ui_lbl315;
extern lv_obj_t * ui_gridGrp630;
extern lv_obj_t * ui_grid630;
extern lv_obj_t * ui_lbl630;
extern lv_obj_t * ui_gridGrp1K;
extern lv_obj_t * ui_grid1K;
extern lv_obj_t * ui_lbl1K;
extern lv_obj_t * ui_gridGrp2K5;
extern lv_obj_t * ui_grid2K5;
extern lv_obj_t * ui_lbl2K5;
extern lv_obj_t * ui_gridGrp5K;
extern lv_obj_t * ui_grid5K;
extern lv_obj_t * ui_lbl5K;
extern lv_obj_t * ui_gridGrp10K;
extern lv_obj_t * ui_grid10K;
extern lv_obj_t * ui_lbl10K;
extern lv_obj_t * ui_graphEQ;
extern lv_obj_t * ui_graphEQ_Xaxis;
extern lv_obj_t * ui_graphEQ_Yaxis1;
extern lv_obj_t * ui_graphEQ_Yaxis2;
extern lv_obj_t * ui_contMeterOutput;
extern lv_obj_t * ui_contOutputMeter;
extern lv_obj_t * ui_lblMetersInput2;
extern lv_obj_t * ui_lblMetersInput3;
extern lv_obj_t * ui_barOutput;
extern lv_obj_t * ui_contControls;
extern lv_obj_t * ui_contHPF;
extern lv_obj_t * ui_lblControlsHPF;
extern lv_obj_t * ui_lblControlsHPF2;
extern lv_obj_t * ui_contWarm;
extern lv_obj_t * ui_lblControlsWarm;
extern lv_obj_t * ui_lblControlsWarm1;
extern lv_obj_t * ui_contPresence;
extern lv_obj_t * ui_lblControlsPres;
extern lv_obj_t * ui_lblControlsPres1;
extern lv_obj_t * ui_contAir;
extern lv_obj_t * ui_lblControlsAir;
extern lv_obj_t * ui_lblControlsAir1;
extern lv_obj_t * ui_contFooter;
extern lv_obj_t * ui_contFootorClick;
extern lv_obj_t * ui_lblSettings;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

