// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef _VOX_PREAMP_UI_UI_H
#define _VOX_PREAMP_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenMain.h"
#include "screens/ui_ScreenGlobal.h"
#include "screens/ui_ScreenWifi.h"
#include "screens/ui_ScreenAudioDSP.h"
#include "screens/ui_ScreenSystem.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icn_usb_png);    // assets/icn_usb.png
LV_IMG_DECLARE(ui_img_bluetooth_ico_png);    // assets/BlueTooth_ico.png
LV_IMG_DECLARE(ui_img_mqtt_svrstack_png);    // assets/MQTT_SvrStack.png
LV_IMG_DECLARE(ui_img_icn_wifi_png);    // assets/icn_wifi.png
LV_IMG_DECLARE(ui_img_mic_ico_png);    // assets/Mic_ico.png
LV_IMG_DECLARE(ui_img_indicator_ver_25seg_png);    // assets/indicator_ver_25seg.png
LV_IMG_DECLARE(ui_img_icn_back_png);    // assets/icn_back.png
LV_IMG_DECLARE(ui_img_icn_forward_png);    // assets/icn_Forward.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
