// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _VOX_EFX_UI_H
#define _VOX_EFX_UI_H

#ifdef __cplusplus
extern "C" {
#endif

//#include "lvgl/lvgl.h"
#include "lvgl.h"


#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Main.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_382037981);    // assets/ChatGPT Image Feb 7, 2026, 07_45_50 PM.png
LV_IMG_DECLARE(ui_img_1980880135);    // assets/ChatGPT Image Feb 7, 2026, 07_54_16 PM.png
LV_IMG_DECLARE(ui_img_1926139265);    // assets/ChatGPT Image Feb 7, 2026, 07_33_48 PM.png
LV_IMG_DECLARE(ui_img_2009663892);    // assets/ChatGPT Image Feb 7, 2026, 07_52_39 PM.png

// FONTS
LV_FONT_DECLARE(ui_font_14_bold);
LV_FONT_DECLARE(ui_font_mos_semibold_16);
LV_FONT_DECLARE(ui_font_number);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
