// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_nav_reverb(lv_event_t * e);
void on_nav_delay(lv_event_t * e);
void on_nav_dynamics(lv_event_t * e);
void on_nav_eq(lv_event_t * e);
void on_nav_setup(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
