// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "ui.h"

static void show_only_panel(lv_obj_t * panel_to_show)
{
    lv_obj_add_flag(ui_pnlReverb,   LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_pnlDelay,    LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_pnlDynamics, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_pnlEQ,       LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_pnlSetup,    LV_OBJ_FLAG_HIDDEN);

    lv_obj_clear_flag(panel_to_show, LV_OBJ_FLAG_HIDDEN);
}

void on_nav_reverb(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    show_only_panel(ui_pnlReverb);
}

void on_nav_delay(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    show_only_panel(ui_pnlDelay);
}

void on_nav_dynamics(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    show_only_panel(ui_pnlDynamics);
}

void on_nav_eq(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    show_only_panel(ui_pnlEQ);
}

void on_nav_setup(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    show_only_panel(ui_pnlSetup);
}

