// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#include "ui.h"

lv_obj_t * ui_ScreenWifi = NULL;
lv_obj_t * ui_contWIFIHeader = NULL;
lv_obj_t * ui_btnBackWIFI = NULL;
lv_obj_t * ui_imgBackArrow2 = NULL;
lv_obj_t * ui_lblWIFI = NULL;
lv_obj_t * ui_contHeaderSpacer2 = NULL;
lv_obj_t * ui_contWIFIContent = NULL;
lv_obj_t * ui_rowSSID = NULL;
lv_obj_t * ui_dropDwnWIFIID = NULL;
lv_obj_t * ui_btnWIFIScan = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_rowPassword = NULL;
lv_obj_t * ui_lblWifiPw = NULL;
lv_obj_t * ui_txtAWIFI = NULL;
lv_obj_t * ui_rowWifiConnect = NULL;
lv_obj_t * ui_btnWIFIConnect = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_contWIFIFooter = NULL;
lv_obj_t * ui_lblWifiStatus = NULL;
// event funtions

// build funtions

void ui_ScreenWifi_screen_init(void)
{
    ui_ScreenWifi = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_ScreenWifi, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ScreenWifi, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_bg_color(ui_ScreenWifi, lv_color_hex(0x0E271F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contWIFIHeader = lv_obj_create(ui_ScreenWifi);
    lv_obj_remove_style_all(ui_contWIFIHeader);
    lv_obj_set_height(ui_contWIFIHeader, 60);
    lv_obj_set_width(ui_contWIFIHeader, lv_pct(100));
    lv_obj_set_x(ui_contWIFIHeader, 1);
    lv_obj_set_y(ui_contWIFIHeader, -133);
    lv_obj_set_align(ui_contWIFIHeader, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_contWIFIHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contWIFIHeader, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contWIFIHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contWIFIHeader, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contWIFIHeader, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBackWIFI = lv_button_create(ui_contWIFIHeader);
    lv_obj_set_width(ui_btnBackWIFI, 80);
    lv_obj_set_height(ui_btnBackWIFI, lv_pct(100));
    lv_obj_set_x(ui_btnBackWIFI, -196);
    lv_obj_set_y(ui_btnBackWIFI, 1);
    lv_obj_set_align(ui_btnBackWIFI, LV_ALIGN_CENTER);
    lv_obj_set_ext_click_area(ui_btnBackWIFI, 10);
    lv_obj_add_flag(ui_btnBackWIFI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnBackWIFI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_btnBackWIFI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBackWIFI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBackWIFI, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBackWIFI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgBackArrow2 = lv_image_create(ui_btnBackWIFI);
    lv_image_set_src(ui_imgBackArrow2, &ui_img_icn_back_png);
    lv_obj_set_width(ui_imgBackArrow2, lv_pct(100));
    lv_obj_set_height(ui_imgBackArrow2, lv_pct(100));
    lv_obj_set_align(ui_imgBackArrow2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgBackArrow2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgBackArrow2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWIFI = lv_label_create(ui_contWIFIHeader);
    lv_obj_set_width(ui_lblWIFI, lv_pct(68));
    lv_obj_set_height(ui_lblWIFI, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWIFI, 4);
    lv_obj_set_y(ui_lblWIFI, 0);
    lv_obj_set_align(ui_lblWIFI, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWIFI, "WIFI");
    lv_obj_set_style_text_color(ui_lblWIFI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblWIFI, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblWIFI, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contHeaderSpacer2 = lv_obj_create(ui_contWIFIHeader);
    lv_obj_remove_style_all(ui_contHeaderSpacer2);
    lv_obj_set_height(ui_contHeaderSpacer2, lv_pct(100));
    lv_obj_set_flex_grow(ui_contHeaderSpacer2, 1);
    lv_obj_set_x(ui_contHeaderSpacer2, 10);
    lv_obj_set_y(ui_contHeaderSpacer2, -17);
    lv_obj_set_align(ui_contHeaderSpacer2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_contHeaderSpacer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_contWIFIContent = lv_obj_create(ui_ScreenWifi);
    lv_obj_remove_style_all(ui_contWIFIContent);
    lv_obj_set_width(ui_contWIFIContent, lv_pct(100));
    lv_obj_set_flex_grow(ui_contWIFIContent, 1);
    lv_obj_set_x(ui_contWIFIContent, -121);
    lv_obj_set_y(ui_contWIFIContent, 103);
    lv_obj_set_align(ui_contWIFIContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_contWIFIContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_contWIFIContent, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_contWIFIContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_contWIFIContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_contWIFIContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_contWIFIContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_contWIFIContent, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contWIFIContent, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contWIFIContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rowSSID = lv_obj_create(ui_contWIFIContent);
    lv_obj_remove_style_all(ui_rowSSID);
    lv_obj_set_width(ui_rowSSID, lv_pct(100));
    lv_obj_set_height(ui_rowSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rowSSID, 130);
    lv_obj_set_y(ui_rowSSID, -51);
    lv_obj_set_align(ui_rowSSID, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowSSID, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rowSSID, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_rowSSID, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_rowSSID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_rowSSID, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropDwnWIFIID = lv_dropdown_create(ui_rowSSID);
    lv_dropdown_set_options(ui_dropDwnWIFIID, "Red Hen");
    lv_dropdown_set_text(ui_dropDwnWIFIID, "Select network");
    lv_obj_set_height(ui_dropDwnWIFIID, 42);
    lv_obj_set_flex_grow(ui_dropDwnWIFIID, 1);
    lv_obj_set_x(ui_dropDwnWIFIID, 55);
    lv_obj_set_y(ui_dropDwnWIFIID, -76);
    lv_obj_set_align(ui_dropDwnWIFIID, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dropDwnWIFIID, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_dropDwnWIFIID, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropDwnWIFIID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_dropDwnWIFIID, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dropDwnWIFIID, lv_color_hex(0x081A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropDwnWIFIID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dropDwnWIFIID, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWIFIScan = lv_button_create(ui_rowSSID);
    lv_obj_set_width(ui_btnWIFIScan, 110);
    lv_obj_set_height(ui_btnWIFIScan, 42);
    lv_obj_set_x(ui_btnWIFIScan, -170);
    lv_obj_set_y(ui_btnWIFIScan, -77);
    lv_obj_set_align(ui_btnWIFIScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnWIFIScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnWIFIScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWIFIScan, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWIFIScan, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWIFIScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnWIFIScan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_btnWIFIScan);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "SCAN");

    ui_rowPassword = lv_obj_create(ui_contWIFIContent);
    lv_obj_remove_style_all(ui_rowPassword);
    lv_obj_set_width(ui_rowPassword, lv_pct(100));
    lv_obj_set_height(ui_rowPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_rowPassword, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rowPassword, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rowPassword, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_rowPassword, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_rowPassword, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_rowPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiPw = lv_label_create(ui_rowPassword);
    lv_obj_set_width(ui_lblWifiPw, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiPw, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblWifiPw, -83);
    lv_obj_set_y(ui_lblWifiPw, 23);
    lv_obj_set_align(ui_lblWifiPw, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiPw, "PASSWORD");
    lv_obj_set_style_text_color(ui_lblWifiPw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiPw, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_txtAWIFI = lv_textarea_create(ui_rowPassword);
    lv_obj_set_height(ui_txtAWIFI, 42);
    lv_obj_set_width(ui_txtAWIFI, lv_pct(100));
    lv_obj_set_x(ui_txtAWIFI, 23);
    lv_obj_set_y(ui_txtAWIFI, 21);
    lv_obj_set_align(ui_txtAWIFI, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_txtAWIFI, "Enter password");
    lv_obj_set_style_bg_color(ui_txtAWIFI, lv_color_hex(0x081A14), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_txtAWIFI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_txtAWIFI, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_txtAWIFI, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_txtAWIFI, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_rowWifiConnect = lv_obj_create(ui_ScreenWifi);
    lv_obj_remove_style_all(ui_rowWifiConnect);
    lv_obj_set_width(ui_rowWifiConnect, lv_pct(100));
    lv_obj_set_height(ui_rowWifiConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_flex_flow(ui_rowWifiConnect, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_rowWifiConnect, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_rowWifiConnect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_rowWifiConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rowWifiConnect, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rowWifiConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rowWifiConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_rowWifiConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_rowWifiConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnWIFIConnect = lv_button_create(ui_rowWifiConnect);
    lv_obj_set_width(ui_btnWIFIConnect, 110);
    lv_obj_set_height(ui_btnWIFIConnect, 42);
    lv_obj_set_x(ui_btnWIFIConnect, -1);
    lv_obj_set_y(ui_btnWIFIConnect, 76);
    lv_obj_add_flag(ui_btnWIFIConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_btnWIFIConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnWIFIConnect, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnWIFIConnect, lv_color_hex(0x184534), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnWIFIConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnWIFIConnect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_btnWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_btnWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_btnWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_btnWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_btnWIFIConnect);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "CONNECT");
    lv_obj_set_style_text_align(ui_Label10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_contWIFIFooter = lv_obj_create(ui_ScreenWifi);
    lv_obj_remove_style_all(ui_contWIFIFooter);
    lv_obj_set_height(ui_contWIFIFooter, 40);
    lv_obj_set_width(ui_contWIFIFooter, lv_pct(100));
    lv_obj_set_x(ui_contWIFIFooter, -1);
    lv_obj_set_y(ui_contWIFIFooter, -1);
    lv_obj_set_align(ui_contWIFIFooter, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_contWIFIFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_contWIFIFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_contWIFIFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_contWIFIFooter, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_contWIFIFooter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_contWIFIFooter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_contWIFIFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_contWIFIFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_contWIFIFooter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblWifiStatus = lv_label_create(ui_contWIFIFooter);
    lv_obj_set_width(ui_lblWifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWifiStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWifiStatus, "Status: Not connected");
    lv_obj_set_style_text_color(ui_lblWifiStatus, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblWifiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ScreenWifi_screen_destroy(void)
{
    if(ui_ScreenWifi) lv_obj_del(ui_ScreenWifi);

    // NULL screen variables
    ui_ScreenWifi = NULL;
    ui_contWIFIHeader = NULL;
    ui_btnBackWIFI = NULL;
    ui_imgBackArrow2 = NULL;
    ui_lblWIFI = NULL;
    ui_contHeaderSpacer2 = NULL;
    ui_contWIFIContent = NULL;
    ui_rowSSID = NULL;
    ui_dropDwnWIFIID = NULL;
    ui_btnWIFIScan = NULL;
    ui_Label9 = NULL;
    ui_rowPassword = NULL;
    ui_lblWifiPw = NULL;
    ui_txtAWIFI = NULL;
    ui_rowWifiConnect = NULL;
    ui_btnWIFIConnect = NULL;
    ui_Label10 = NULL;
    ui_contWIFIFooter = NULL;
    ui_lblWifiStatus = NULL;

}
