// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef UI_SCREENAUDIODSP_H
#define UI_SCREENAUDIODSP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenAudioDSP
extern void ui_ScreenAudioDSP_screen_init(void);
extern void ui_ScreenAudioDSP_screen_destroy(void);
extern lv_obj_t * ui_ScreenAudioDSP;
extern lv_obj_t * ui_contAudioDSPHeader;
extern lv_obj_t * ui_btnBackAudioDSP;
extern lv_obj_t * ui_imgBackArrow5;
extern lv_obj_t * ui_lblAudioDSP;
extern lv_obj_t * ui_contHeaderSpacer5;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_swCompEnable;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_swNoiseGateEnable;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

