// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef UI_SCREENGLOBAL_H
#define UI_SCREENGLOBAL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenGlobal
extern void ui_ScreenGlobal_screen_init(void);
extern void ui_ScreenGlobal_screen_destroy(void);
extern lv_obj_t * ui_ScreenGlobal;
extern lv_obj_t * ui_contGBLHeader;
extern lv_obj_t * ui_btnBackGBLSettings;
extern lv_obj_t * ui_imgBackArrow;
extern lv_obj_t * ui_lblGBLSettings;
extern lv_obj_t * ui_contHeaderSpacer;
extern lv_obj_t * ui_contGBLContent;
extern lv_obj_t * ui_contBtnAudio;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_contBtnWIFI;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_contBtnSystem;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

