// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_PREAMP_UI

#ifndef UI_SCREENWIFI_H
#define UI_SCREENWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWifi
extern void ui_ScreenWifi_screen_init(void);
extern void ui_ScreenWifi_screen_destroy(void);
extern lv_obj_t * ui_ScreenWifi;
extern lv_obj_t * ui_contWIFIHeader;
extern lv_obj_t * ui_btnBackWIFI;
extern lv_obj_t * ui_imgBackArrow2;
extern lv_obj_t * ui_lblWIFI;
extern lv_obj_t * ui_contHeaderSpacer2;
extern lv_obj_t * ui_contWIFIContent;
extern lv_obj_t * ui_rowSSID;
extern lv_obj_t * ui_dropDwnWIFIID;
extern lv_obj_t * ui_btnWIFIScan;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_rowPassword;
extern lv_obj_t * ui_lblWifiPw;
extern lv_obj_t * ui_txtAWIFI;
extern lv_obj_t * ui_rowWifiConnect;
extern lv_obj_t * ui_btnWIFIConnect;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_contWIFIFooter;
extern lv_obj_t * ui_lblWifiStatus;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

