// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: VOX_EFX

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_PanelBG[2] = {0x242424, 0x242424};
const ui_theme_variable_t _ui_theme_alpha_PanelBG[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_PANELCARD;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

