[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_protocol = teensy-cli

monitor_speed = 115200
board_build.usb_type = none

lib_deps =
  https://github.com/PaulStoffregen/Audio.git
  https://github.com/PaulStoffregen/SerialFlash.git

lib_ldf_mode = deep+

build_unflags = -Os
build_flags =
  -O2
  -DAUDIO_BLOCK_SAMPLES=128